name: Get The List of Build Variants From Asana
description: |
  Fetch the lists of build variants to measure retention (ATB) and attribution (Origin) from different Asana projects and combine them in a list.
inputs:
  access-token:
    description: "Asana access token"
    required: true
  github-token:
    description: "GitHub Token"
    required: false
  atb-asana-task-id:
    description: "Asana Task id for the ATB list."
    required: true
  origin-asana-section-id:
    description: "Asana Section id for the Origins list"
    required: true
  variants-per-job:
    description: "Number of variants that a single job creates."
    required: false
    default: "10"
outputs:
  build-variants:
    description: "The GitHub Actions matrix of build variant batches to create, one entry per job."
    value: ${{ steps.get-build-variants-task.outputs.build-variants }}
runs:
  using: "composite"
  steps:
    - id: get-build-variants-task
      shell: bash
      env:
        ASANA_ACCESS_TOKEN: ${{ inputs.access-token }}
        GITHUB_TOKEN: ${{ inputs.github-token || github.token }}
        ORIGIN_ASANA_SECTION_ID: ${{ inputs.origin-asana-section-id }}
        ATB_ASANA_TASK_ID: ${{ inputs.atb-asana-task-id }}
        VARIANTS_PER_JOB: ${{ inputs.variants-per-job }}
      run: |
        ${{ github.action_path }}/get_build_variants_list.sh
