//
//  DefaultColorPalette.swift
//
//  Copyright © 2025 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import SwiftUI

/// Autogenerated from [Figma](https://www.figma.com/design/3W4vi0zX8hrpQc7zInQQB6/%F0%9F%8E%A8-Global-Colors---Styles?m=dev)
/// Do not edit by hand — re-export from Figma and regenerate.
struct DefaultColorPalette: SharedColorPaletteDefinition {

    // MARK: - Surface
    static let surfaceBackdrop = DynamicColor(lightHex: 0xE4E4E4, darkHex: 0x050505)
    static let surfaceCanvas = DynamicColor(lightHex: 0xFDFDFD, darkHex: 0x1C1C1C)
    static let surfacePrimary = DynamicColor(lightHex: 0xF8F8F8, darkHex: 0x222222)
    static let surfaceSecondary = DynamicColor(lightHex: 0xFCFCFC, darkHex: 0x2B2B2B)
    static let surfaceTertiary = DynamicColor(lightHex: 0xFFFFFF, darkHex: 0x333333)
    static let surfaceContrast = DynamicColor(lightHex: 0x000000, lightOpacity: 0.96,
                                              darkHex: 0xFFFFFF, darkOpacity: 0.96)
    static let surfaceDecorationPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.09,
                                                       darkHex: 0xFFFFFF, darkOpacity: 0.12)
    static let surfaceDecorationSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.16,
                                                         darkHex: 0xFFFFFF, darkOpacity: 0.2)
    static let surfaceDecorationTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.24,
                                                        darkHex: 0xFFFFFF, darkOpacity: 0.32)

    // MARK: - Container
    static let containerFillPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.02,
                                                   darkHex: 0xFFFFFF, darkOpacity: 0.01)
    static let containerFillSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.03,
                                                     darkHex: 0xFFFFFF, darkOpacity: 0.06)
    static let containerFillTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.04,
                                                    darkHex: 0xFFFFFF, darkOpacity: 0.09)
    static let containerBorderPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.06,
                                                     darkHex: 0xFFFFFF, darkOpacity: 0.09)
    static let containerBorderSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.09,
                                                       darkHex: 0xFFFFFF, darkOpacity: 0.12)
    static let containerBorderTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.12,
                                                      darkHex: 0xFFFFFF, darkOpacity: 0.18)

    // MARK: - Text
    static let textPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.96, darkHex: 0xFFFFFF, darkOpacity: 1)
    static let textSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.6, darkHex: 0xFFFFFF, darkOpacity: 0.7)
    static let textTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.36, darkHex: 0xFFFFFF, darkOpacity: 0.4)

    // MARK: - Icons
    static let iconsPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.84, darkHex: 0xFFFFFF, darkOpacity: 0.78)
    static let iconsSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.6,
                                             darkHex: 0xFFFFFF, darkOpacity: 0.48)
    static let iconsTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.36,
                                            darkHex: 0xFFFFFF, darkOpacity: 0.24)

    // MARK: - Accent
    static let accentPrimary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater60,
                                            darkColor: PrimitiveColor.Pondwater.pondwater40)
    static let accentSecondary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater70,
                                              darkColor: PrimitiveColor.Pondwater.pondwater50)
    static let accentTertiary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater80,
                                             darkColor: PrimitiveColor.Pondwater.pondwater60)
    static let accentQuaternary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater90,
                                               darkColor: PrimitiveColor.Pondwater.pondwater70)
    static let accentGlowPrimary = DynamicColor(lightHex: 0x1074CC, lightOpacity: 0.2,
                                                darkHex: 0x75B6EB, darkOpacity: 0.2)
    static let accentGlowSecondary = DynamicColor(lightHex: 0x1074CC, lightOpacity: 0.12,
                                                  darkHex: 0x75B6EB, darkOpacity: 0.12)
    static let accentTextPrimary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater60,
                                                darkColor: PrimitiveColor.Pondwater.pondwater40)
    static let accentTextSecondary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater70,
                                                  darkColor: PrimitiveColor.Pondwater.pondwater50)
    static let accentTextTertiary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater80,
                                                 darkColor: PrimitiveColor.Pondwater.pondwater60)
    static let accentContentPrimary = DynamicColor(lightColor: Color(0xFFFFFF),
                                                   darkColor: PrimitiveColor.Eggshell.eggshell90)
    static let accentContentSecondary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.7,
                                                     darkHex: 0x111111, darkOpacity: 0.7)
    static let accentContentTertiary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.5,
                                                    darkHex: 0x111111, darkOpacity: 0.5)

    // MARK: - Accent-Alt
    static let accentAltPrimary = DynamicColor(lightHex: 0xD6EFFF, darkHex: 0x194776)
    static let accentAltSecondary = DynamicColor(lightHex: 0xB4D9F9, darkHex: 0x133F6C)
    static let accentAltTertiary = DynamicColor(lightHex: 0x90C4EF, darkHex: 0x0F3A66)
    static let accentAltGlowPrimary = DynamicColor(lightHex: 0xA1CFF7, lightOpacity: 0.16,
                                                   darkHex: 0xA1CFF7, darkOpacity: 0.12)
    static let accentAltGlowSecondary = DynamicColor(lightHex: 0xA1CFF7, lightOpacity: 0.08,
                                                     darkHex: 0xA1CFF7, darkOpacity: 0.08)
    static let accentAltTextPrimary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater70,
                                                   darkColor: PrimitiveColor.Pondwater.pondwater0)
    static let accentAltTextSecondary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater80,
                                                     darkColor: PrimitiveColor.Pondwater.pondwater10)
    static let accentAltTextTertiary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater90,
                                                    darkColor: PrimitiveColor.Pondwater.pondwater20)
    static let accentAltContentPrimary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater90,
                                                      darkColor: PrimitiveColor.Pondwater.pondwater0)
    static let accentAltContentSecondary = DynamicColor(lightColor: Color(0x02254D).opacity(0.72),
                                                        darkColor: PrimitiveColor.Pondwater.pondwater0)
    static let accentAltContentTertiary = DynamicColor(lightColor: Color(0x02254D).opacity(0.48),
                                                       darkColor: PrimitiveColor.GrayScale.white)

    // MARK: - Accent-Fire
    static let accentFirePrimary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin50,
                                                darkColor: PrimitiveColor.Mandarin.mandarin40)
    static let accentFireSecondary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin60,
                                                  darkColor: PrimitiveColor.Mandarin.mandarin50)
    static let accentFireTertiary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin70,
                                                 darkColor: PrimitiveColor.Mandarin.mandarin60)
    static let accentFireGlowPrimary = DynamicColor(lightHex: 0xF05F2B, lightOpacity: 0.2,
                                                    darkHex: 0xFF8D5C, darkOpacity: 0.2)
    static let accentFireGlowSecondary = DynamicColor(lightHex: 0xF05F2B, lightOpacity: 0.12,
                                                      darkHex: 0xFF8D5C, darkOpacity: 0.12)
    static let accentFireTextPrimary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin50,
                                                    darkColor: PrimitiveColor.Mandarin.mandarin40)
    static let accentFireTextSecondary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin60,
                                                      darkColor: PrimitiveColor.Mandarin.mandarin50)
    static let accentFireTextTertiary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin70,
                                                     darkColor: PrimitiveColor.Mandarin.mandarin60)
    static let accentFireContentPrimary = DynamicColor(lightHex: 0xFFFFFF, darkHex: 0xFFFFFF)
    static let accentFireContentSecondary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.7,
                                                         darkHex: 0xFFFFFF, darkOpacity: 0.7)
    static let accentFireContentTertiary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.5,
                                                        darkHex: 0xFFFFFF, darkOpacity: 0.5)

    // MARK: - Accent-Brand
    static let accentBrandPrimary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin50,
                                                 darkColor: PrimitiveColor.Pollen.pollen40)
    static let accentBrandSecondary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin60,
                                                   darkColor: PrimitiveColor.Pollen.pollen50)
    static let accentBrandTertiary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin70,
                                                  darkColor: PrimitiveColor.Pollen.pollen60)
    static let accentBrandGlowPrimary = DynamicColor(lightHex: 0xF05F2B, lightOpacity: 0.2,
                                                     darkHex: 0xFFC95C, darkOpacity: 0.2)
    static let accentBrandGlowSecondary = DynamicColor(lightHex: 0xF05F2B, lightOpacity: 0.12,
                                                       darkHex: 0xFFC95C, darkOpacity: 0.12)
    static let accentBrandTextPrimary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin50,
                                                     darkColor: PrimitiveColor.Pollen.pollen30)
    static let accentBrandTextSecondary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin60,
                                                       darkColor: PrimitiveColor.Pollen.pollen40)
    static let accentBrandTextTertiary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin70,
                                                      darkColor: PrimitiveColor.Pollen.pollen50)
    static let accentBrandContentPrimary = DynamicColor(lightColor: PrimitiveColor.GrayScale.white,
                                                        darkColor: PrimitiveColor.Pollen.pollen100)
    static let accentBrandContentSecondary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.7,
                                                          darkHex: 0x1A0B03, darkOpacity: 0.72)
    static let accentBrandContentTertiary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.5,
                                                         darkHex: 0x1A0B03, darkOpacity: 0.48)

    // MARK: - Control
    static let controlFillPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.06,
                                                 darkHex: 0xFFFFFF, darkOpacity: 0.06)
    static let controlFillSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.09,
                                                   darkHex: 0xFFFFFF, darkOpacity: 0.09)
    static let controlFillTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.12,
                                                  darkHex: 0xFFFFFF, darkOpacity: 0.12)
    static let controlBorderPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.3,
                                                   darkHex: 0xFFFFFF, darkOpacity: 0.36)
    static let controlBorderSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.48,
                                                     darkHex: 0xFFFFFF, darkOpacity: 0.64)
    static let controlBorderTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.6,
                                                    darkHex: 0xFFFFFF, darkOpacity: 0.72)
    static let controlBorderQuaternary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.72,
                                                      darkHex: 0xFFFFFF, darkOpacity: 0.8)

    // MARK: - Control-Subtle
    static let controlSubtleFillPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.02,
                                                       darkHex: 0xFFFFFF, darkOpacity: 0.03)
    static let controlSubtleFillSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.05,
                                                         darkHex: 0xFFFFFF, darkOpacity: 0.06)
    static let controlSubtleFillTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.08,
                                                        darkHex: 0xFFFFFF, darkOpacity: 0.12)
    static let controlSubtleBorderPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.12,
                                                         darkHex: 0xFFFFFF, darkOpacity: 0.12)
    static let controlSubtleBorderSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.18,
                                                           darkHex: 0xFFFFFF, darkOpacity: 0.18)
    static let controlSubtleBorderTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.36,
                                                          darkHex: 0xFFFFFF, darkOpacity: 0.36)

    // MARK: - Control-Raised
    static let controlRaisedFillPrimary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 1,
                                                       darkHex: 0xFFFFFF, darkOpacity: 0.18)
    static let controlRaisedFillSecondary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.84,
                                                         darkHex: 0xFFFFFF, darkOpacity: 0.14)
    static let controlRaisedFillTertiary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 1,
                                                        darkHex: 0xFFFFFF, darkOpacity: 0.18)
    static let controlRaisedBackdrop = DynamicColor(lightHex: 0x000000, lightOpacity: 0.09,
                                                    darkHex: 0xFFFFFF, darkOpacity: 0.12)

    // MARK: - Unified-Input
    static let unifiedInputFillPrimary = DynamicColor(lightHex: 0xFFFFFF,
                                                      darkHex: 0xFFFFFF)  // light-only in Figma; dark mirrors light
    static let unifiedInputFieldFillActive = DynamicColor(lightHex: 0xFFFFFF, darkHex: 0x333333)
    static let unifiedInputFieldFillResting = DynamicColor(lightHex: 0xEBEBEB, darkHex: 0x090909)

    // MARK: - Highlight
    static let highlightPrimary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.24,
                                               darkHex: 0xF9F9F9, darkOpacity: 0.12)

    // MARK: - Tone
    static let toneTintPrimary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.32,
                                              darkHex: 0xFFFFFF, darkOpacity: 0.06)
    static let toneTintSecondary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.6,
                                                darkHex: 0xFFFFFF, darkOpacity: 0.12)
    static let toneShadePrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.03,
                                               darkHex: 0x000000, darkOpacity: 0.12)

    // MARK: - Shadow
    static let shadowPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.05,
                                            darkHex: 0x000000, darkOpacity: 0.16)
    static let shadowSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.08,
                                              darkHex: 0x000000, darkOpacity: 0.24)
    static let shadowTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.16,
                                             darkHex: 0x000000, darkOpacity: 0.32)

    // MARK: - Destructive
    static let destructivePrimary = DynamicColor(lightColor: PrimitiveColor.Red.red50,
                                                 darkColor: PrimitiveColor.Red.red40)
    static let destructiveSecondary = DynamicColor(lightColor: PrimitiveColor.Red.red60,
                                                   darkColor: PrimitiveColor.Red.red50)
    static let destructiveTertiary = DynamicColor(lightColor: PrimitiveColor.Red.red70,
                                                  darkColor: PrimitiveColor.Red.red60)
    static let destructiveGlowPrimary = DynamicColor(lightHex: 0xE5244B, lightOpacity: 0.2,
                                                     darkHex: 0xEE6D87, darkOpacity: 0.2)
    static let destructiveGlowSecondary = DynamicColor(lightHex: 0xE5244B, lightOpacity: 0.2,
                                                       darkHex: 0xEE6D87, darkOpacity: 0.12)
    static let destructiveTextPrimary = DynamicColor(lightColor: PrimitiveColor.Red.red60,
                                                     darkColor: PrimitiveColor.Red.red30)
    static let destructiveTextSecondary = DynamicColor(lightColor: PrimitiveColor.Red.red70,
                                                       darkColor: PrimitiveColor.Red.red40)
    static let destructiveTextTertiary = DynamicColor(lightColor: PrimitiveColor.Red.red80,
                                                      darkColor: PrimitiveColor.Red.red50)
    static let destructiveContentPrimary = DynamicColor(lightColor: PrimitiveColor.GrayScale.white,
                                                        darkColor: Color(0x000000))
    static let destructiveContentSecondary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.9,
                                                          darkHex: 0x000000, darkOpacity: 0.9)
    static let destructiveContentTertiary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.6,
                                                         darkHex: 0x000000, darkOpacity: 0.6)

    // MARK: - Status
    static let statusGreen = DynamicColor(lightColor: PrimitiveColor.Green.green40,
                                          darkColor: PrimitiveColor.Green.green40)
    static let statusYellowPrimary = DynamicColor(lightColor: PrimitiveColor.Pollen.pollen50,
                                                  darkColor: PrimitiveColor.Pollen.pollen50)
    static let statusYellowSecondary = DynamicColor(lightColor: PrimitiveColor.Pollen.pollen40,
                                                    darkColor: PrimitiveColor.Pollen.pollen40)
    static let statusYellowTertiary = DynamicColor(lightColor: PrimitiveColor.Pollen.pollen30,
                                                   darkColor: PrimitiveColor.Pollen.pollen30)
    static let statusRed = DynamicColor(lightColor: PrimitiveColor.Red.red50, darkColor: Color(0xFF545A))
    static let statusGray = DynamicColor(lightColor: PrimitiveColor.GrayScale.gray40, darkColor: Color(0xAAAAAA))

    // MARK: - Status-Warning
    static let statusWarningPrimary = DynamicColor(lightColor: PrimitiveColor.Pollen.pollen40,
                                                   darkColor: PrimitiveColor.Pollen.pollen30)
    static let statusWarningContentPrimary = DynamicColor(lightColor: Color(0x191101), darkColor: Color(0x191101))
    static let statusWarningFillPrimary = DynamicColor(lightColor: Color(0xFFE699).opacity(0.32),
                                                       darkColor: Color(0xFFB200).opacity(0.12))
}
