//
//  OnboardingColorPalette.swift
//
//  Copyright © 2026 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import SwiftUI

/// Autogenerated from [Figma](https://www.figma.com/design/3W4vi0zX8hrpQc7zInQQB6/%F0%9F%8E%A8-Global-Colors---Styles?m=dev)
/// Do not edit by hand — re-export from Figma and regenerate.
struct OnboardingColorPalette: SharedColorPaletteDefinition {

    // MARK: - Surface
    static let surfaceBackdrop = DynamicColor(lightColor: PrimitiveColor.GrayScale.white, darkColor: Color(0x133E7C))
    static let surfaceCanvas = DynamicColor(lightColor: PrimitiveColor.GrayScale.white,
                                            darkColor: PrimitiveColor.GrayScale.black)
    static let surfacePrimary = DynamicColor(lightColor: PrimitiveColor.Eggshell.eggshell20, darkColor: Color(0x123269))
    static let surfaceSecondary = DynamicColor(lightColor: PrimitiveColor.Eggshell.eggshell10,
                                               darkColor: Color(0x051E3D))
    static let surfaceTertiary = DynamicColor(lightColor: PrimitiveColor.GrayScale.white, darkColor: Color(0x011D34))
    static let surfaceContrast = DynamicColor(lightHex: 0x242323, lightOpacity: 0.96,
                                              darkHex: 0xFFFFFF, darkOpacity: 0.96)
    static let surfaceDecorationPrimary = DynamicColor(lightHex: 0x242323, lightOpacity: 0.09,
                                                       darkHex: 0xFFFFFF, darkOpacity: 0.06)
    static let surfaceDecorationSecondary = DynamicColor(lightHex: 0x242323, lightOpacity: 0.16,
                                                         darkHex: 0xFFFFFF, darkOpacity: 0.09)
    static let surfaceDecorationTertiary = DynamicColor(lightHex: 0x242323, lightOpacity: 0.24,
                                                        darkHex: 0xFFFFFF, darkOpacity: 0.2)

    // MARK: - Container
    static let containerFillPrimary = DynamicColor(lightHex: 0x242323, lightOpacity: 0.01,
                                                   darkHex: 0xFFFFFF, darkOpacity: 0.01)
    static let containerFillSecondary = DynamicColor(lightHex: 0x242323, lightOpacity: 0.03,
                                                     darkHex: 0xFFFFFF, darkOpacity: 0.06)
    static let containerFillTertiary = DynamicColor(lightHex: 0x242323, lightOpacity: 0.06,
                                                    darkHex: 0xFFFFFF, darkOpacity: 0.09)
    static let containerBorderPrimary = DynamicColor(lightHex: 0x242323, lightOpacity: 0.06,
                                                     darkHex: 0xFFFFFF, darkOpacity: 0.09)
    static let containerBorderSecondary = DynamicColor(lightHex: 0x242323, lightOpacity: 0.09,
                                                       darkHex: 0xFFFFFF, darkOpacity: 0.12)
    static let containerBorderTertiary = DynamicColor(lightHex: 0x242323, lightOpacity: 0.12,
                                                      darkHex: 0xFFFFFF, darkOpacity: 0.18)

    // MARK: - Text
    static let textPrimary = DynamicColor(lightColor: Color(0x242323).opacity(0.96),
                                          darkColor: PrimitiveColor.GrayScale.white)
    static let textSecondary = DynamicColor(lightColor: Color(0x242323).opacity(0.6),
                                            darkColor: PrimitiveColor.Eggshell.eggshell30)
    static let textTertiary = DynamicColor(lightColor: Color(0x242323).opacity(0.36),
                                           darkColor: PrimitiveColor.Eggshell.eggshell50)

    // MARK: - Icons
    static let iconsPrimary = DynamicColor(lightHex: 0x242323, lightOpacity: 0.84, darkHex: 0xFBFAF9, darkOpacity: 0.78)
    static let iconsSecondary = DynamicColor(lightHex: 0x383838, lightOpacity: 0.6,
                                             darkHex: 0xFBFAF9, darkOpacity: 0.48)
    static let iconsTertiary = DynamicColor(lightHex: 0x242323, lightOpacity: 0.4, darkHex: 0xFBFAF9, darkOpacity: 0.48)

    // MARK: - Accent
    static let accentPrimary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater50,
                                            darkColor: PrimitiveColor.Pondwater.pondwater40)
    static let accentSecondary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater60,
                                              darkColor: PrimitiveColor.Pondwater.pondwater50)
    static let accentTertiary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater60,
                                             darkColor: PrimitiveColor.Pondwater.pondwater60)
    static let accentQuaternary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater70,
                                               darkColor: PrimitiveColor.Pondwater.pondwater70)
    static let accentGlowPrimary = DynamicColor(lightHex: 0x2F95EE, lightOpacity: 0.2,
                                                darkHex: 0x75B6EB, darkOpacity: 0.16)
    static let accentGlowSecondary = DynamicColor(lightHex: 0x2F95EE, lightOpacity: 0.12,
                                                  darkHex: 0x75B6EB, darkOpacity: 0.12)
    static let accentTextPrimary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater60,
                                                darkColor: PrimitiveColor.Pondwater.pondwater40)
    static let accentTextSecondary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater70,
                                                  darkColor: PrimitiveColor.Pondwater.pondwater50)
    static let accentTextTertiary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater80,
                                                 darkColor: PrimitiveColor.Pondwater.pondwater60)
    static let accentContentPrimary = DynamicColor(lightColor: Color(0xFFFFFF),
                                                   darkColor: PrimitiveColor.Eggshell.eggshell90)
    static let accentContentSecondary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.7,
                                                     darkHex: 0x111111, darkOpacity: 0.7)
    static let accentContentTertiary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.5,
                                                    darkHex: 0x111111, darkOpacity: 0.5)

    // MARK: - Accent-Alt
    static let accentAltPrimary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater20,
                                               darkColor: Color(0x133E7C))
    static let accentAltSecondary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater30,
                                                 darkColor: Color(0x722408))
    static let accentAltTertiary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater30,
                                                darkColor: Color(0x99300B))
    static let accentAltGlowPrimary = DynamicColor(lightHex: 0xA1CFF7, lightOpacity: 0.16,
                                                   darkHex: 0xA1CFF7, darkOpacity: 0.12)
    static let accentAltGlowSecondary = DynamicColor(lightHex: 0xA1CFF7, lightOpacity: 0.08,
                                                     darkHex: 0xA1CFF7, darkOpacity: 0.08)
    static let accentAltTextPrimary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater60,
                                                   darkColor: Color(0xF8B7A0))
    static let accentAltTextSecondary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater70,
                                                     darkColor: Color(0xF69B79))
    static let accentAltTextTertiary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater80,
                                                    darkColor: Color(0xF37E53))
    static let accentAltContentPrimary = DynamicColor(lightHex: 0x0C2031, darkHex: 0xF8B7A0)
    static let accentAltContentSecondary = DynamicColor(lightHex: 0x0C2031, lightOpacity: 0.7,
                                                        darkHex: 0xFCE2D9, darkOpacity: 1)
    static let accentAltContentTertiary = DynamicColor(lightColor: Color(0x0C2031).opacity(0.5),
                                                       darkColor: Color(0xFFFFFF))

    // MARK: - Accent-Fire
    static let accentFirePrimary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin50,
                                                darkColor: PrimitiveColor.Mandarin.mandarin40)
    static let accentFireSecondary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin60,
                                                  darkColor: PrimitiveColor.Mandarin.mandarin50)
    static let accentFireTertiary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin70,
                                                 darkColor: PrimitiveColor.Mandarin.mandarin60)
    static let accentFireGlowPrimary = DynamicColor(lightHex: 0xF05F2B, lightOpacity: 0.16,
                                                    darkHex: 0xFF8D5C, darkOpacity: 0.2)
    static let accentFireGlowSecondary = DynamicColor(lightHex: 0xF05F2B, lightOpacity: 0.08,
                                                      darkHex: 0xFF8D5C, darkOpacity: 0.12)
    static let accentFireTextPrimary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin50,
                                                    darkColor: PrimitiveColor.Mandarin.mandarin40)
    static let accentFireTextSecondary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin60,
                                                      darkColor: PrimitiveColor.Mandarin.mandarin50)
    static let accentFireTextTertiary = DynamicColor(lightColor: PrimitiveColor.Mandarin.mandarin70,
                                                     darkColor: PrimitiveColor.Mandarin.mandarin60)
    static let accentFireContentPrimary = DynamicColor(lightHex: 0xFFFFFF, darkHex: 0xFFFFFF)
    static let accentFireContentSecondary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.7,
                                                         darkHex: 0xFFFFFF, darkOpacity: 0.7)
    static let accentFireContentTertiary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.5,
                                                        darkHex: 0xFFFFFF, darkOpacity: 0.5)

    // MARK: - Accent-Brand
    static let accentBrandPrimary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater20,
                                                 darkColor: PrimitiveColor.Pondwater.pondwater20)
    static let accentBrandSecondary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater30,
                                                   darkColor: PrimitiveColor.Pondwater.pondwater30)
    static let accentBrandTertiary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater30,
                                                  darkColor: PrimitiveColor.Pondwater.pondwater30)
    static let accentBrandGlowPrimary = DynamicColor(lightHex: 0xA1CFF7, lightOpacity: 0.16,
                                                     darkHex: 0xA1CFF7, darkOpacity: 0.16)
    static let accentBrandGlowSecondary = DynamicColor(lightHex: 0xA1CFF7, lightOpacity: 0.08,
                                                       darkHex: 0xA1CFF7, darkOpacity: 0.08)
    static let accentBrandTextPrimary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater60,
                                                     darkColor: PrimitiveColor.Pondwater.pondwater60)
    static let accentBrandTextSecondary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater70,
                                                       darkColor: PrimitiveColor.Pondwater.pondwater70)
    static let accentBrandTextTertiary = DynamicColor(lightColor: PrimitiveColor.Pondwater.pondwater80,
                                                      darkColor: PrimitiveColor.Pondwater.pondwater80)
    static let accentBrandContentPrimary = DynamicColor(lightHex: 0x0C2031, darkHex: 0x0C2031)
    static let accentBrandContentSecondary = DynamicColor(lightHex: 0x0C2031, lightOpacity: 0.7,
                                                          darkHex: 0x0C2031, darkOpacity: 0.7)
    static let accentBrandContentTertiary = DynamicColor(lightHex: 0x0C2031, lightOpacity: 0.5,
                                                         darkHex: 0x0C2031, darkOpacity: 0.5)

    // MARK: - Control
    static let controlFillPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.06,
                                                 darkHex: 0xFFFFFF, darkOpacity: 0.12)
    static let controlFillSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.09,
                                                   darkHex: 0xFFFFFF, darkOpacity: 0.18)
    static let controlFillTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.12,
                                                  darkHex: 0xFFFFFF, darkOpacity: 0.24)
    static let controlBorderPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.2,
                                                   darkHex: 0xFFFFFF, darkOpacity: 0.36)
    static let controlBorderSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.24,
                                                     darkHex: 0xFFFFFF, darkOpacity: 0.64)
    static let controlBorderTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.28,
                                                    darkHex: 0xFFFFFF, darkOpacity: 0.72)
    static let controlBorderQuaternary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.32,
                                                      darkHex: 0xFFFFFF, darkOpacity: 0.8)

    // MARK: - Control-Subtle
    static let controlSubtleFillPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.02,
                                                       darkHex: 0xFFFFFF, darkOpacity: 0.03)
    static let controlSubtleFillSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.05,
                                                         darkHex: 0xFFFFFF, darkOpacity: 0.06)
    static let controlSubtleFillTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.08,
                                                        darkHex: 0xFFFFFF, darkOpacity: 0.12)
    static let controlSubtleBorderPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.12,
                                                         darkHex: 0xFFFFFF, darkOpacity: 0.12)
    static let controlSubtleBorderSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.18,
                                                           darkHex: 0xFFFFFF, darkOpacity: 0.18)
    static let controlSubtleBorderTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.36,
                                                          darkHex: 0xFFFFFF, darkOpacity: 0.36)

    // MARK: - Control-Raised
    static let controlRaisedFillPrimary = DynamicColor(lightHex: 0xFFFFFF, darkHex: 0xFFFFFF)
    static let controlRaisedFillSecondary = DynamicColor(lightHex: 0xFFFFFF, darkHex: 0xFFFFFF)
    static let controlRaisedFillTertiary = DynamicColor(lightHex: 0xFFFFFF, darkHex: 0xFFFFFF)
    static let controlRaisedBackdrop = DynamicColor(lightHex: 0x000000, lightOpacity: 0.09,
                                                    darkHex: 0x000000, darkOpacity: 0.09)

    // MARK: - Unified-Input
    static let unifiedInputFillPrimary = DynamicColor(lightColor: PrimitiveColor.GrayScale.white,
                                                      darkColor: PrimitiveColor.GrayScale.white)  // light-only in Figma; dark mirrors light
    static let unifiedInputFieldFillActive = DynamicColor(lightColor: PrimitiveColor.GrayScale.white,
                                                          darkColor: Color(0x011D34))
    static let unifiedInputFieldFillResting = DynamicColor(lightColor: PrimitiveColor.GrayScale.white,
                                                           darkColor: Color(0x011D34))

    // MARK: - Highlight
    static let highlightPrimary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.24,
                                               darkHex: 0xFFFFFF, darkOpacity: 0.24)

    // MARK: - Tone
    static let toneTintPrimary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.6,
                                              darkHex: 0xCCDAFF, darkOpacity: 0.12)
    static let toneTintSecondary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.84,
                                                darkHex: 0xCCDAFF, darkOpacity: 0.24)
    static let toneShadePrimary = DynamicColor(lightHex: 0x242323, lightOpacity: 0.03,
                                               darkHex: 0x000000, darkOpacity: 0.06)

    // MARK: - Shadow
    static let shadowPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.05,
                                            darkHex: 0x000000, darkOpacity: 0.05)
    static let shadowSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.08,
                                              darkHex: 0x000000, darkOpacity: 0.08)
    static let shadowTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.16,
                                             darkHex: 0x000000, darkOpacity: 0.16)

    // MARK: - Destructive
    static let destructivePrimary = DynamicColor(lightColor: PrimitiveColor.Red.red50,
                                                 darkColor: PrimitiveColor.Red.red30)
    static let destructiveSecondary = DynamicColor(lightColor: PrimitiveColor.Red.red60,
                                                   darkColor: PrimitiveColor.Red.red20)
    static let destructiveTertiary = DynamicColor(lightColor: PrimitiveColor.Red.red70,
                                                  darkColor: PrimitiveColor.Red.red10)
    static let destructiveGlowPrimary = DynamicColor(lightHex: 0xE5244B, lightOpacity: 0.2,
                                                     darkHex: 0xEE6D87, darkOpacity: 0.2)
    static let destructiveGlowSecondary = DynamicColor(lightHex: 0xE5244B, lightOpacity: 0.12,
                                                       darkHex: 0xEE6D87, darkOpacity: 0.12)
    static let destructiveTextPrimary = DynamicColor(lightColor: PrimitiveColor.Red.red50,
                                                     darkColor: PrimitiveColor.Red.red30)
    static let destructiveTextSecondary = DynamicColor(lightColor: PrimitiveColor.Red.red60,
                                                       darkColor: PrimitiveColor.Red.red20)
    static let destructiveTextTertiary = DynamicColor(lightColor: PrimitiveColor.Red.red70,
                                                      darkColor: PrimitiveColor.Red.red10)
    static let destructiveContentPrimary = DynamicColor(lightColor: PrimitiveColor.GrayScale.white,
                                                        darkColor: PrimitiveColor.GrayScale.white)
    static let destructiveContentSecondary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.9,
                                                          darkHex: 0xFFFFFF, darkOpacity: 0.9)
    static let destructiveContentTertiary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.6,
                                                         darkHex: 0xFFFFFF, darkOpacity: 0.6)

    // MARK: - Status
    static let statusGreen = DynamicColor(lightColor: PrimitiveColor.Lilypad.lilypad60,
                                          darkColor: PrimitiveColor.Lilypad.lilypad30)
    static let statusYellowPrimary = DynamicColor(lightColor: Color(0xFFCC00), darkColor: Color(0xFFCC00))
    static let statusYellowSecondary = DynamicColor(lightColor: Color(0xFFC95C), darkColor: Color(0xFFCC00))
    static let statusYellowTertiary = DynamicColor(lightColor: Color(0xFFCC00), darkColor: Color(0xFFCC00))
    static let statusRed = DynamicColor(lightColor: PrimitiveColor.Red.red50, darkColor: PrimitiveColor.Red.red30)
    static let statusGray = DynamicColor(lightColor: Color(0xAAAAAA), darkColor: Color(0xAAAAAA))

    // MARK: - Status-Warning
    static let statusWarningPrimary = DynamicColor(lightColor: PrimitiveColor.Pollen.pollen40,
                                                   darkColor: PrimitiveColor.Pollen.pollen30)
    static let statusWarningContentPrimary = DynamicColor(lightColor: PrimitiveColor.Pollen.pollen40,
                                                          darkColor: PrimitiveColor.Pollen.pollen30)
    static let statusWarningFillPrimary = DynamicColor(lightColor: PrimitiveColor.Pollen.pollen40,
                                                       darkColor: PrimitiveColor.Pollen.pollen30)
}
