//
//  SharedColorPaletteDefinition+Resolver.swift
//
//  Copyright © 2026 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import Foundation
import SwiftUI

/// Autogenerated from [Figma](https://www.figma.com/design/3W4vi0zX8hrpQc7zInQQB6/%F0%9F%8E%A8-Global-Colors---Styles?m=dev)
/// Do not edit by hand — re-export from Figma and regenerate.
extension SharedColorPaletteDefinition {

    /// Resolves a semantic colour against this palette. Figma-backed tokens come from the
    /// palette itself; the rest come from `ManualColorTokens`, which is palette-independent.
    static func dynamicColor(for designSystemColor: SharedDesignSystemColor) -> DynamicColor {
        switch designSystemColor {
        // Surface
        case .surfaceBackdrop: return surfaceBackdrop
        case .surfaceCanvas: return surfaceCanvas
        case .surfacePrimary: return surfacePrimary
        case .surfaceSecondary: return surfaceSecondary
        case .surfaceTertiary: return surfaceTertiary
        case .surfaceContrast: return surfaceContrast
        case .surfaceDecorationPrimary: return surfaceDecorationPrimary
        case .surfaceDecorationSecondary: return surfaceDecorationSecondary
        case .surfaceDecorationTertiary: return surfaceDecorationTertiary
        // Container
        case .containerFillPrimary: return containerFillPrimary
        case .containerFillSecondary: return containerFillSecondary
        case .containerFillTertiary: return containerFillTertiary
        case .containerBorderPrimary: return containerBorderPrimary
        case .containerBorderSecondary: return containerBorderSecondary
        case .containerBorderTertiary: return containerBorderTertiary
        // Text
        case .textPrimary: return textPrimary
        case .textSecondary: return textSecondary
        case .textTertiary: return textTertiary
        // Icons
        case .iconsPrimary: return iconsPrimary
        case .iconsSecondary: return iconsSecondary
        case .iconsTertiary: return iconsTertiary
        // Accent
        case .accentPrimary: return accentPrimary
        case .accentSecondary: return accentSecondary
        case .accentTertiary: return accentTertiary
        case .accentQuaternary: return accentQuaternary
        case .accentGlowPrimary: return accentGlowPrimary
        case .accentGlowSecondary: return accentGlowSecondary
        case .accentTextPrimary: return accentTextPrimary
        case .accentTextSecondary: return accentTextSecondary
        case .accentTextTertiary: return accentTextTertiary
        case .accentContentPrimary: return accentContentPrimary
        case .accentContentSecondary: return accentContentSecondary
        case .accentContentTertiary: return accentContentTertiary
        // Accent-Alt
        case .accentAltPrimary: return accentAltPrimary
        case .accentAltSecondary: return accentAltSecondary
        case .accentAltTertiary: return accentAltTertiary
        case .accentAltGlowPrimary: return accentAltGlowPrimary
        case .accentAltGlowSecondary: return accentAltGlowSecondary
        case .accentAltTextPrimary: return accentAltTextPrimary
        case .accentAltTextSecondary: return accentAltTextSecondary
        case .accentAltTextTertiary: return accentAltTextTertiary
        case .accentAltContentPrimary: return accentAltContentPrimary
        case .accentAltContentSecondary: return accentAltContentSecondary
        case .accentAltContentTertiary: return accentAltContentTertiary
        // Accent-Fire
        case .accentFirePrimary: return accentFirePrimary
        case .accentFireSecondary: return accentFireSecondary
        case .accentFireTertiary: return accentFireTertiary
        case .accentFireGlowPrimary: return accentFireGlowPrimary
        case .accentFireGlowSecondary: return accentFireGlowSecondary
        case .accentFireTextPrimary: return accentFireTextPrimary
        case .accentFireTextSecondary: return accentFireTextSecondary
        case .accentFireTextTertiary: return accentFireTextTertiary
        case .accentFireContentPrimary: return accentFireContentPrimary
        case .accentFireContentSecondary: return accentFireContentSecondary
        case .accentFireContentTertiary: return accentFireContentTertiary
        // Accent-Brand
        case .accentBrandPrimary: return accentBrandPrimary
        case .accentBrandSecondary: return accentBrandSecondary
        case .accentBrandTertiary: return accentBrandTertiary
        case .accentBrandGlowPrimary: return accentBrandGlowPrimary
        case .accentBrandGlowSecondary: return accentBrandGlowSecondary
        case .accentBrandTextPrimary: return accentBrandTextPrimary
        case .accentBrandTextSecondary: return accentBrandTextSecondary
        case .accentBrandTextTertiary: return accentBrandTextTertiary
        case .accentBrandContentPrimary: return accentBrandContentPrimary
        case .accentBrandContentSecondary: return accentBrandContentSecondary
        case .accentBrandContentTertiary: return accentBrandContentTertiary
        // Control
        case .controlFillPrimary: return controlFillPrimary
        case .controlFillSecondary: return controlFillSecondary
        case .controlFillTertiary: return controlFillTertiary
        case .controlBorderPrimary: return controlBorderPrimary
        case .controlBorderSecondary: return controlBorderSecondary
        case .controlBorderTertiary: return controlBorderTertiary
        case .controlBorderQuaternary: return controlBorderQuaternary
        // Control-Subtle
        case .controlSubtleFillPrimary: return controlSubtleFillPrimary
        case .controlSubtleFillSecondary: return controlSubtleFillSecondary
        case .controlSubtleFillTertiary: return controlSubtleFillTertiary
        case .controlSubtleBorderPrimary: return controlSubtleBorderPrimary
        case .controlSubtleBorderSecondary: return controlSubtleBorderSecondary
        case .controlSubtleBorderTertiary: return controlSubtleBorderTertiary
        // Control-Raised
        case .controlRaisedFillPrimary: return controlRaisedFillPrimary
        case .controlRaisedFillSecondary: return controlRaisedFillSecondary
        case .controlRaisedFillTertiary: return controlRaisedFillTertiary
        case .controlRaisedBackdrop: return controlRaisedBackdrop
        // Unified-Input
        case .unifiedInputFillPrimary: return unifiedInputFillPrimary
        case .unifiedInputFieldFillActive: return unifiedInputFieldFillActive
        case .unifiedInputFieldFillResting: return unifiedInputFieldFillResting
        // Highlight
        case .highlightPrimary: return highlightPrimary
        // Tone
        case .toneTintPrimary: return toneTintPrimary
        case .toneTintSecondary: return toneTintSecondary
        case .toneShadePrimary: return toneShadePrimary
        // Shadow
        case .shadowPrimary: return shadowPrimary
        case .shadowSecondary: return shadowSecondary
        case .shadowTertiary: return shadowTertiary
        // Destructive
        case .destructivePrimary: return destructivePrimary
        case .destructiveSecondary: return destructiveSecondary
        case .destructiveTertiary: return destructiveTertiary
        case .destructiveGlowPrimary: return destructiveGlowPrimary
        case .destructiveGlowSecondary: return destructiveGlowSecondary
        case .destructiveTextPrimary: return destructiveTextPrimary
        case .destructiveTextSecondary: return destructiveTextSecondary
        case .destructiveTextTertiary: return destructiveTextTertiary
        case .destructiveContentPrimary: return destructiveContentPrimary
        case .destructiveContentSecondary: return destructiveContentSecondary
        case .destructiveContentTertiary: return destructiveContentTertiary
        // Status
        case .statusGreen: return statusGreen
        case .statusYellowPrimary: return statusYellowPrimary
        case .statusYellowSecondary: return statusYellowSecondary
        case .statusYellowTertiary: return statusYellowTertiary
        case .statusRed: return statusRed
        case .statusGray: return statusGray
        // Status-Warning
        case .statusWarningPrimary: return statusWarningPrimary
        case .statusWarningContentPrimary: return statusWarningContentPrimary
        case .statusWarningFillPrimary: return statusWarningFillPrimary
        // Manual tokens
        case .alertGreen: return ManualColorTokens.alertGreen
        case .alertYellow: return ManualColorTokens.alertYellow
        case .vpnGreen: return ManualColorTokens.vpnGreen
        case .vpnGreenPressed: return ManualColorTokens.vpnGreenPressed
        case .vpnGreenForeground: return ManualColorTokens.vpnGreenForeground
        case .vpnGreenForegroundPressed: return ManualColorTokens.vpnGreenForegroundPressed
        case .vpnYellow: return ManualColorTokens.vpnYellow
        case .vpnYellowPressed: return ManualColorTokens.vpnYellowPressed
        case .vpnYellowForeground: return ManualColorTokens.vpnYellowForeground
        case .vpnYellowForegroundPressed: return ManualColorTokens.vpnYellowForegroundPressed
        case .shieldPrivacy: return ManualColorTokens.shieldPrivacy
        case .buttonsWhite: return ManualColorTokens.buttonsWhite
        case .buttonsPrimaryDefault: return ManualColorTokens.buttonsPrimaryDefault
        case .buttonsPrimaryPressed: return ManualColorTokens.buttonsPrimaryPressed
        case .buttonsPrimaryDisabled: return ManualColorTokens.buttonsPrimaryDisabled
        case .buttonsPrimaryText: return ManualColorTokens.buttonsPrimaryText
        case .buttonsPrimaryTextDisabled: return ManualColorTokens.buttonsPrimaryTextDisabled
        case .buttonsSecondaryFillDefault: return ManualColorTokens.buttonsSecondaryFillDefault
        case .buttonsSecondaryFillPressed: return ManualColorTokens.buttonsSecondaryFillPressed
        case .buttonsSecondaryFillDisabled: return ManualColorTokens.buttonsSecondaryFillDisabled
        case .buttonsSecondaryFillText: return ManualColorTokens.buttonsSecondaryFillText
        case .buttonsSecondaryFillTextDisabled: return ManualColorTokens.buttonsSecondaryFillTextDisabled
        case .lines: return ManualColorTokens.lines
        case .spinnerStart: return ManualColorTokens.spinnerStart
        case .spinnerFinal: return ManualColorTokens.spinnerFinal
        case .textSuccess: return ManualColorTokens.textSuccess
        case .textLink: return ManualColorTokens.textLink
        case .backgroundTertiary: return ManualColorTokens.backgroundTertiary
        case .backgroundSheets: return ManualColorTokens.backgroundSheets
        case .backgroundPromptMessage: return ManualColorTokens.backgroundPromptMessage
        case .urlBar: return ManualColorTokens.urlBar
        case .surfaceDecorationQuaternary: return ManualColorTokens.surfaceDecorationQuaternary
        case .border: return ManualColorTokens.border
        case .textPlaceholder: return ManualColorTokens.textPlaceholder
        case .buttonsSecondaryWireDefault: return ManualColorTokens.buttonsSecondaryWireDefault
        case .buttonsSecondaryWirePressedFill: return ManualColorTokens.buttonsSecondaryWirePressedFill
        case .buttonsSecondaryWireDisabledStroke: return ManualColorTokens.buttonsSecondaryWireDisabledStroke
        case .buttonsSecondaryWireText: return ManualColorTokens.buttonsSecondaryWireText
        case .buttonsSecondaryWireTextPressed: return ManualColorTokens.buttonsSecondaryWireTextPressed
        case .buttonsSecondaryWireTextDisabled: return ManualColorTokens.buttonsSecondaryWireTextDisabled
        case .buttonsGhostPressedFill: return ManualColorTokens.buttonsGhostPressedFill
        case .buttonsGhostText: return ManualColorTokens.buttonsGhostText
        case .buttonsGhostTextPressed: return ManualColorTokens.buttonsGhostTextPressed
        case .buttonsGhostTextDisabled: return ManualColorTokens.buttonsGhostTextDisabled
        case .buttonsDeleteGhostPressedFill: return ManualColorTokens.buttonsDeleteGhostPressedFill
        case .buttonsDeleteGhostText: return ManualColorTokens.buttonsDeleteGhostText
        case .buttonsDeleteGhostTextPressed: return ManualColorTokens.buttonsDeleteGhostTextPressed
        case .buttonsDeleteGhostTextDisabled: return ManualColorTokens.buttonsDeleteGhostTextDisabled
        case .buttonsDestructivePrimaryPressed: return ManualColorTokens.buttonsDestructivePrimaryPressed
        case .permissionCenterBackground: return ManualColorTokens.permissionCenterBackground
        case .permissionCenterContainerBackground: return ManualColorTokens.permissionCenterContainerBackground
        case .permissionWarningBackground: return ManualColorTokens.permissionWarningBackground
        case .permissionReloadButtonBackground: return ManualColorTokens.permissionReloadButtonBackground
        case .permissionReloadButtonText: return ManualColorTokens.permissionReloadButtonText
        // Palette-backed names
        case .textSelectionFill: return accentGlowPrimary
        }
    }
}
