//
//  SharedColorPaletteDefinition.swift
//
//  Copyright © 2025 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import Foundation

/// Autogenerated from [Figma](https://www.figma.com/design/3W4vi0zX8hrpQc7zInQQB6/%F0%9F%8E%A8-Global-Colors---Styles?m=dev)
/// Do not edit by hand — re-export from Figma and regenerate.
protocol SharedColorPaletteDefinition {

    // MARK: - Surface
    static var surfaceBackdrop: DynamicColor { get }
    static var surfaceCanvas: DynamicColor { get }
    static var surfacePrimary: DynamicColor { get }
    static var surfaceSecondary: DynamicColor { get }
    static var surfaceTertiary: DynamicColor { get }
    static var surfaceContrast: DynamicColor { get }
    static var surfaceDecorationPrimary: DynamicColor { get }
    static var surfaceDecorationSecondary: DynamicColor { get }
    static var surfaceDecorationTertiary: DynamicColor { get }

    // MARK: - Container
    static var containerFillPrimary: DynamicColor { get }
    static var containerFillSecondary: DynamicColor { get }
    static var containerFillTertiary: DynamicColor { get }
    static var containerBorderPrimary: DynamicColor { get }
    static var containerBorderSecondary: DynamicColor { get }
    static var containerBorderTertiary: DynamicColor { get }

    // MARK: - Text
    static var textPrimary: DynamicColor { get }
    static var textSecondary: DynamicColor { get }
    static var textTertiary: DynamicColor { get }

    // MARK: - Icons
    static var iconsPrimary: DynamicColor { get }
    static var iconsSecondary: DynamicColor { get }
    static var iconsTertiary: DynamicColor { get }

    // MARK: - Accent
    static var accentPrimary: DynamicColor { get }
    static var accentSecondary: DynamicColor { get }
    static var accentTertiary: DynamicColor { get }
    static var accentQuaternary: DynamicColor { get }
    static var accentGlowPrimary: DynamicColor { get }
    static var accentGlowSecondary: DynamicColor { get }
    static var accentTextPrimary: DynamicColor { get }
    static var accentTextSecondary: DynamicColor { get }
    static var accentTextTertiary: DynamicColor { get }
    static var accentContentPrimary: DynamicColor { get }
    static var accentContentSecondary: DynamicColor { get }
    static var accentContentTertiary: DynamicColor { get }

    // MARK: - Accent-Alt
    static var accentAltPrimary: DynamicColor { get }
    static var accentAltSecondary: DynamicColor { get }
    static var accentAltTertiary: DynamicColor { get }
    static var accentAltGlowPrimary: DynamicColor { get }
    static var accentAltGlowSecondary: DynamicColor { get }
    static var accentAltTextPrimary: DynamicColor { get }
    static var accentAltTextSecondary: DynamicColor { get }
    static var accentAltTextTertiary: DynamicColor { get }
    static var accentAltContentPrimary: DynamicColor { get }
    static var accentAltContentSecondary: DynamicColor { get }
    static var accentAltContentTertiary: DynamicColor { get }

    // MARK: - Accent-Fire
    static var accentFirePrimary: DynamicColor { get }
    static var accentFireSecondary: DynamicColor { get }
    static var accentFireTertiary: DynamicColor { get }
    static var accentFireGlowPrimary: DynamicColor { get }
    static var accentFireGlowSecondary: DynamicColor { get }
    static var accentFireTextPrimary: DynamicColor { get }
    static var accentFireTextSecondary: DynamicColor { get }
    static var accentFireTextTertiary: DynamicColor { get }
    static var accentFireContentPrimary: DynamicColor { get }
    static var accentFireContentSecondary: DynamicColor { get }
    static var accentFireContentTertiary: DynamicColor { get }

    // MARK: - Accent-Brand
    static var accentBrandPrimary: DynamicColor { get }
    static var accentBrandSecondary: DynamicColor { get }
    static var accentBrandTertiary: DynamicColor { get }
    static var accentBrandGlowPrimary: DynamicColor { get }
    static var accentBrandGlowSecondary: DynamicColor { get }
    static var accentBrandTextPrimary: DynamicColor { get }
    static var accentBrandTextSecondary: DynamicColor { get }
    static var accentBrandTextTertiary: DynamicColor { get }
    static var accentBrandContentPrimary: DynamicColor { get }
    static var accentBrandContentSecondary: DynamicColor { get }
    static var accentBrandContentTertiary: DynamicColor { get }

    // MARK: - Control
    static var controlFillPrimary: DynamicColor { get }
    static var controlFillSecondary: DynamicColor { get }
    static var controlFillTertiary: DynamicColor { get }
    static var controlBorderPrimary: DynamicColor { get }
    static var controlBorderSecondary: DynamicColor { get }
    static var controlBorderTertiary: DynamicColor { get }
    static var controlBorderQuaternary: DynamicColor { get }

    // MARK: - Control-Subtle
    static var controlSubtleFillPrimary: DynamicColor { get }
    static var controlSubtleFillSecondary: DynamicColor { get }
    static var controlSubtleFillTertiary: DynamicColor { get }
    static var controlSubtleBorderPrimary: DynamicColor { get }
    static var controlSubtleBorderSecondary: DynamicColor { get }
    static var controlSubtleBorderTertiary: DynamicColor { get }

    // MARK: - Control-Raised
    static var controlRaisedFillPrimary: DynamicColor { get }
    static var controlRaisedFillSecondary: DynamicColor { get }
    static var controlRaisedFillTertiary: DynamicColor { get }
    static var controlRaisedBackdrop: DynamicColor { get }

    // MARK: - Unified-Input
    static var unifiedInputFillPrimary: DynamicColor { get }
    static var unifiedInputFieldFillActive: DynamicColor { get }
    static var unifiedInputFieldFillResting: DynamicColor { get }

    // MARK: - Highlight
    static var highlightPrimary: DynamicColor { get }

    // MARK: - Tone
    static var toneTintPrimary: DynamicColor { get }
    static var toneTintSecondary: DynamicColor { get }
    static var toneShadePrimary: DynamicColor { get }

    // MARK: - Shadow
    static var shadowPrimary: DynamicColor { get }
    static var shadowSecondary: DynamicColor { get }
    static var shadowTertiary: DynamicColor { get }

    // MARK: - Destructive
    static var destructivePrimary: DynamicColor { get }
    static var destructiveSecondary: DynamicColor { get }
    static var destructiveTertiary: DynamicColor { get }
    static var destructiveGlowPrimary: DynamicColor { get }
    static var destructiveGlowSecondary: DynamicColor { get }
    static var destructiveTextPrimary: DynamicColor { get }
    static var destructiveTextSecondary: DynamicColor { get }
    static var destructiveTextTertiary: DynamicColor { get }
    static var destructiveContentPrimary: DynamicColor { get }
    static var destructiveContentSecondary: DynamicColor { get }
    static var destructiveContentTertiary: DynamicColor { get }

    // MARK: - Status
    static var statusGreen: DynamicColor { get }
    static var statusYellowPrimary: DynamicColor { get }
    static var statusYellowSecondary: DynamicColor { get }
    static var statusYellowTertiary: DynamicColor { get }
    static var statusRed: DynamicColor { get }
    static var statusGray: DynamicColor { get }

    // MARK: - Status-Warning
    static var statusWarningPrimary: DynamicColor { get }
    static var statusWarningContentPrimary: DynamicColor { get }
    static var statusWarningFillPrimary: DynamicColor { get }
}
