//
//  WebExtensionImportScriptsShim.swift
//
//  Copyright © 2026 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import Foundation

/// JavaScript injected into the background page generated by `WebExtensionBackgroundPagePatcher`,
/// after the API stubs and before the extension's own background script, whenever that script is a
/// classic (non-module) service worker bundle.
///
/// `importScripts` is a Worker global: a background page does not have it. A classic webpack bundle
/// built for a service worker uses it to load its split chunks, and does so synchronously at the top
/// level — the Bitwarden 2026.8.0 bundle reaches
/// `o.f.i=(t,i)=>{e[t]||importScripts(o.p+o.u(t))}` about 1.7 MB into `background.js` — so on a page
/// the very first chunk load is a `ReferenceError` and the extension never bootstraps.
///
/// The patcher preloads every chunk file it can find with an ordinary `<script src>` tag ahead of the
/// bundle, which is necessary but not sufficient: a chunk's payload is
/// `(self.webpackChunk_x = self.webpackChunk_x || []).push([[719], {…}])`, and the worker-flavored
/// webpack runtime does not replay entries that are already in that array — it only replaces the
/// array's `push` and then consults `installedChunks`, finding the chunk missing and calling
/// `importScripts`. What does work, measured on macOS 26.6.2, is calling `array.push(entry)` again
/// once the runtime has installed its own `push`: the runtime then registers the modules and
/// resolves the pending chunk. That is exactly what this shim does, from inside `importScripts`.
///
/// Two further details make the substitution safe:
/// - the shim replays *every* captured entry on the first call, whichever url was requested. A
///   webpack chunk id cannot be mapped back to a file name in general (`o.u` is bundle-specific), and
///   installing a chunk earlier than the runtime asked for is harmless — the runtime keys off
///   `installedChunks`, so an already-installed chunk short-circuits;
/// - a url with no matching preloaded `<script>` throws instead of quietly doing nothing, so a bundle
///   whose chunk naming we failed to predict fails loudly at the point of the missing file rather
///   than much later with a confusing error.
///
/// Defining `importScripts` also fixes webpack's public path probe, which does
/// `o.g.importScripts && (e = o.g.location + "")`: with the global present, the bundle derives its
/// public path from the background page URL minus its last path segment, which is the extension root.
enum WebExtensionImportScriptsShim {

    /// Name of the shim script, written next to `manifest.json`.
    static let filename = "ddg-import-scripts.js"

    static let source = """
    // Generated by DuckDuckGo. Defines `importScripts` for a service worker bundle running as a
    // background page, replaying the webpack chunks the page preloaded instead of fetching them.
    (function() {
        "use strict";

        if (globalThis.importScripts) {
            return;
        }

        // Chunk payloads are arrays; a WeakSet keeps track of the ones already handed to the
        // runtime without holding on to them.
        var replayedEntries = new WeakSet();

        function resolveURL(url) {
            return new URL(url, globalThis.location.href).href;
        }

        // The page preloads chunk files with ordinary <script src> tags, so a requested url is only
        // servable if one of those tags points at it.
        function isPreloaded(resolvedURL) {
            var scripts = (globalThis.document && globalThis.document.scripts) || [];
            for (var index = 0; index < scripts.length; index++) {
                var source = scripts[index] && scripts[index].src;
                if (!source) {
                    continue;
                }
                try {
                    if (resolveURL(source) === resolvedURL) {
                        return true;
                    }
                } catch (error) {
                    // A script tag with an unparseable src cannot be the one we are looking for.
                }
            }
            return false;
        }

        // Hands every captured chunk payload back to whatever `push` the webpack runtime installed,
        // which is what makes the runtime register the chunk's modules.
        function replayCapturedChunks() {
            Object.getOwnPropertyNames(globalThis).forEach(function(name) {
                if (name.indexOf("webpackChunk") !== 0) {
                    return;
                }

                var chunks;
                try {
                    chunks = globalThis[name];
                } catch (error) {
                    return;
                }
                if (!Array.isArray(chunks)) {
                    return;
                }

                // The runtime's `push` appends to the array as well, so iterate a snapshot.
                chunks.slice().forEach(function(entry) {
                    if (!entry || (typeof entry !== "object" && typeof entry !== "function")) {
                        return;
                    }
                    if (replayedEntries.has(entry)) {
                        return;
                    }
                    // Mark before pushing: the runtime's `push` can call back into `importScripts`.
                    replayedEntries.add(entry);
                    try {
                        chunks.push(entry);
                    } catch (error) {
                        console.info("[DuckDuckGo] importScripts: replaying a chunk of " + name + " failed: " + error);
                    }
                });
            });
        }

        globalThis.importScripts = function() {
            for (var index = 0; index < arguments.length; index++) {
                var url = String(arguments[index]);
                if (!isPreloaded(resolveURL(url))) {
                    throw new Error("[DuckDuckGo] importScripts: " + url + " was not preloaded by the background page");
                }
                replayCapturedChunks();
            }
        };
    })();

    """
}
