//
//  WebExtensionAPIStubScript.swift
//
//  Copyright © 2026 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import Foundation

/// JavaScript that defines placeholders for the `chrome.*` APIs WebKit doesn't implement, so an
/// extension built for Chrome keeps running when it uses them instead of throwing.
///
/// A placeholder accepts any call and does nothing: it answers `undefined`, or an empty value where
/// callers read from the result, like `storage.managed.get()`. Only missing names are filled, so the
/// APIs WebKit implements are left alone. The script does nothing in our own extensions, and it
/// reports calls to placeholders to the API compatibility log.
///
/// `chrome.idle` is implemented rather than a placeholder, on macOS: the state (`locked`, `idle` or
/// `active`) comes from the app through `idleMessageHandlerName`, and `onStateChanged` polls while it
/// has listeners.
public enum WebExtensionAPIStubScript {

    /// Property on `globalThis` holding the objects the script decorated, so WebKit's native
    /// namespace wrappers stay alive along with the stubs installed on them.
    static let retentionPropertyName = "__ddgRetainedExtensionAPINamespaces"

    /// Name of the script message handler `chrome.idle.queryState` asks for the idle state. It is
    /// optional: a page with no handler of this name hears `active`.
    public static let idleMessageHandlerName = "ddgWebExtensionIdle"

    public static let source = """
    // Generated by DuckDuckGo. Defines inert stubs for chrome.* APIs that WebKit does not
    // implement, so an extension's background script survives touching them at the top level.
    (function() {
        "use strict";

        // Whichever global the host exposes. We deliberately do not alias `chrome` to `browser`
        // (or the other way round) — that is WebKit's call to make, not ours.
        var api = globalThis.chrome || globalThis.browser;
        if (!api) {
            return;
        }

        // The script must leave ordinary web content alone: some websites define their own
        // `window.chrome` object to look like Chrome, and they must not get stubs installed on it,
        // nor the retention array leaked into them. Only extension pages are served over
        // `webkit-extension:`. A bare `JSContext` in tests has no `location`, so an absent
        // `location` still lets the script run.
        try {
            if (globalThis.location !== undefined && typeof globalThis.location.protocol === "string"
                && globalThis.location.protocol !== "webkit-extension:") {
                return;
            }
        } catch (error) {
            // Reading `location` should not throw; if it does, treat the frame as not ours.
            return;
        }

        // Our own extensions (autoconsent, content blocker, Dark Reader, …) declare
        // `browser_specific_settings.duckduckgo` and need no Chrome shims. Keep in sync with
        // `WKWebExtension.needsChromeCompatibility`.
        try {
            var settings = api.runtime && typeof api.runtime.getManifest === "function"
                ? api.runtime.getManifest().browser_specific_settings : undefined;
            if (settings && settings.duckduckgo) {
                return;
            }
        } catch (error) {
            // A page that cannot read its manifest is treated like any other extension page.
        }

        // Namespaces WebKit does not define at all. Each becomes a generic nestable stub, or a
        // purpose-shaped one when it has a `kind` (see makeIdle below).
        var missingNamespaces = [
            { name: "notifications" },
            { name: "offscreen" },
            { name: "downloads" },
            { name: "idle", kind: "idle" },
            { name: "management" },
            { name: "privacy" },
            { name: "browsingData" },
            { name: "topSites" },
            { name: "sidePanel" }
        ];

        // Members missing from namespaces that WebKit does implement, addressed by dotted path.
        // A "namespace" member becomes a nestable stub, an "event" member an addListener object, and
        // "managedStorage" a purpose-shaped stub (see makeManagedStorage below).
        var missingMembers = [
            { path: "storage.managed", kind: "managedStorage" },
            { path: "webNavigation.onCreatedNavigationTarget", kind: "event" },
            { path: "runtime.onSuspend", kind: "event" }
        ];

        var retentionPropertyName = "\(Self.retentionPropertyName)";
        var eventNamePattern = /^on[A-Z]/;
        var stubDescription = "[DuckDuckGo API stub]";

        // WebKit hands out short-lived wrapper objects for its native namespaces and throws away
        // anything we added to one as soon as JavaScript stops referencing it. Parking every
        // decorated object here keeps both the wrapper and its stubs alive for the whole session.
        var retained = globalThis[retentionPropertyName];
        if (!Array.isArray(retained)) {
            retained = [];
            try {
                Object.defineProperty(globalThis, retentionPropertyName, {
                    value: retained,
                    writable: false,
                    enumerable: false,
                    configurable: true
                });
            } catch (error) {
                globalThis[retentionPropertyName] = retained;
            }
        }

        function retain(object) {
            // `globalThis` outlives everything, so keeping it here would only add noise.
            if (object && object !== globalThis && retained.indexOf(object) === -1) {
                retained.push(object);
            }
        }

        retain(api);

        // Reports a stub call through `WebExtensionAPICompatibilityScript`, which runs first in the same
        // pages. Without it, nothing is reported.
        function reportAPI(kind, path) {
            try {
                var report = globalThis["\(WebExtensionAPICompatibilityScript.reportFunctionName)"];
                if (typeof path === "string" && typeof report === "function") {
                    report(kind, path);
                }
            } catch (error) {
                // Reporting must never disturb the page.
            }
        }

        // Hands a trailing Chrome-style callback its value once, out of band, so a throwing
        // callback cannot take down the caller. Its error is thrown again from a timer, where it
        // surfaces as an uncaught error the page and the compatibility log can see.
        function invokeCallback(callback, value) {
            Promise.resolve().then(function() {
                try {
                    callback(value);
                } catch (error) {
                    setTimeout(function() {
                        throw error;
                    }, 0);
                }
            });
        }

        // A stubbed API method that answers with `makeValue()`, promise-style and callback-style.
        function makeResolver(makeValue) {
            return function() {
                var value = makeValue();
                var callback = arguments.length > 0 ? arguments[arguments.length - 1] : undefined;
                if (typeof callback === "function") {
                    invokeCallback(callback, value);
                }
                return Promise.resolve(value);
            };
        }

        // Hands a trailing callback the value the promise settles with, and returns the promise, the
        // way Chrome's dual-style APIs behave. The callback stays silent if the promise rejects.
        function answerBothStyles(promise, callback) {
            if (typeof callback === "function") {
                promise.then(function(value) {
                    invokeCallback(callback, value);
                }, function() {});
            }
            return promise;
        }

        // `path`, when given, names the API for the compatibility log: registering a listener counts
        // as using a stub. The events inside working shims pass no path.
        function makeEvent(path) {
            return {
                addListener: function() {
                    reportAPI("stubbed", path === undefined ? undefined : path + ".addListener");
                },
                removeListener: function() {},
                hasListener: function() {
                    return false;
                },
                hasListeners: function() {
                    return false;
                }
            };
        }

        // A callable, infinitely nestable placeholder: `chrome.privacy.services.passwordSavingEnabled.get()`
        // resolves through it without ever throwing, and any `onSomething` property is an event object.
        // `path` is the stub's API path, reported when it is called; reading a property is not a use.
        // A namespace (`isNamespace`) is an object, like Chrome's, so only its members can be called.
        function makeStub(path, isNamespace) {
            var children = Object.create(null);

            return new Proxy(isNamespace ? {} : function() {}, {
                get: function(target, property) {
                    if (property === "then") {
                        // Never look like a thenable: awaiting or resolving a namespace must not hang.
                        return undefined;
                    }
                    if (property === Symbol.toPrimitive) {
                        return function() {
                            return stubDescription;
                        };
                    }
                    if (property === "toString") {
                        return function() {
                            return stubDescription;
                        };
                    }
                    if (typeof property !== "string") {
                        return undefined;
                    }
                    if (!isNamespace && (property === "call" || property === "apply" || property === "bind")) {
                        // `stub.call(...)` is a call of the stub itself: the function's own methods must
                        // not extend the API path, or `chrome.downloads.download.call(...)` would be
                        // reported as `chrome.downloads.download.call`.
                        return Reflect.get(target, property);
                    }
                    if (!(property in children)) {
                        var childPath = path + "." + property;
                        children[property] = eventNamePattern.test(property) ? makeEvent(childPath) : makeStub(childPath);
                    }
                    return children[property];
                },
                apply: function(target, thisArgument, argumentsList) {
                    // `JSON.stringify` and `valueOf()` call these on any object; they are not API use.
                    if (!/\\.(toJSON|valueOf)$/.test(path)) {
                        reportAPI("stubbed", path);
                    }
                    // Support both API styles: hand `undefined` to a trailing callback, and return a
                    // promise for callers that await instead.
                    var callback = argumentsList.length > 0 ? argumentsList[argumentsList.length - 1] : undefined;
                    if (typeof callback === "function") {
                        invokeCallback(callback, undefined);
                    }
                    return Promise.resolve(undefined);
                }
            });
        }

        // `storage.managed` needs more than the generic stub: Chrome resolves `get()` to an object
        // (empty when no policy is set) and extensions read a key straight off the result, so
        // resolving to `undefined` would throw at their call site rather than ours. Every call gets
        // a fresh object, so a caller mutating one result cannot leak into the next.
        function makeManagedStorage() {
            return {
                get: makeResolver(function() {
                    return {};
                }),
                getBytesInUse: makeResolver(function() {
                    return 0;
                }),
                onChanged: makeEvent()
            };
        }

        var idleMessageHandlerName = "\(Self.idleMessageHandlerName)";
        var idleStates = ["active", "idle", "locked"];
        var idleDefaultDetectionInterval = 60;
        // Chrome's lower bound for a detection interval, in seconds.
        var idleMinimumDetectionInterval = 15;
        var idlePollIntervalInMilliseconds = 15000;

        function clampIdleDetectionInterval(seconds) {
            var value = Math.floor(Number(seconds));
            return isFinite(value) ? Math.max(idleMinimumDetectionInterval, value) : idleDefaultDetectionInterval;
        }

        // Asks the app for the idle state. Never rejects: no handler, a failed reply or an unknown
        // answer all read as `active`.
        function askForIdleState(detectionInterval) {
            try {
                var handlers = globalThis.webkit && globalThis.webkit.messageHandlers;
                var handler = handlers && handlers[idleMessageHandlerName];
                if (!handler || typeof handler.postMessage !== "function") {
                    return Promise.resolve("active");
                }
                return Promise.resolve(handler.postMessage({ detectionInterval: detectionInterval })).then(function(state) {
                    return idleStates.indexOf(state) !== -1 ? state : "active";
                }, function() {
                    return "active";
                });
            } catch (error) {
                return Promise.resolve("active");
            }
        }

        // `chrome.idle`. While `onStateChanged` has listeners, a single timer polls the app and the
        // listeners hear about changes only; the state before the first answer is `active`.
        function makeIdle() {
            var detectionInterval = idleDefaultDetectionInterval;
            var listeners = [];
            var timer = null;
            var lastState = "active";
            var isPolling = false;

            function poll() {
                if (isPolling) {
                    return;
                }
                isPolling = true;
                askForIdleState(detectionInterval).then(function(state) {
                    isPolling = false;
                    if (state === lastState) {
                        return;
                    }
                    lastState = state;
                    listeners.slice().forEach(function(listener) {
                        try {
                            listener(state);
                        } catch (error) {
                            console.info("[DuckDuckGo] An idle.onStateChanged listener threw: " + error);
                        }
                    });
                });
            }

            var idle = {
                queryState: function(seconds) {
                    var callback = arguments.length > 1 ? arguments[arguments.length - 1] : undefined;
                    return answerBothStyles(askForIdleState(clampIdleDetectionInterval(seconds)), callback);
                },
                setDetectionInterval: function(seconds) {
                    detectionInterval = clampIdleDetectionInterval(seconds);
                },
                getAutoLockDelay: makeResolver(function() {
                    return 0;
                }),
                onStateChanged: {
                    addListener: function(listener) {
                        if (typeof listener !== "function" || listeners.indexOf(listener) !== -1) {
                            return;
                        }
                        listeners.push(listener);
                        if (timer === null) {
                            timer = setInterval(poll, idlePollIntervalInMilliseconds);
                        }
                    },
                    removeListener: function(listener) {
                        var index = listeners.indexOf(listener);
                        if (index === -1) {
                            return;
                        }
                        listeners.splice(index, 1);
                        if (listeners.length === 0 && timer !== null) {
                            clearInterval(timer);
                            timer = null;
                        }
                    },
                    hasListener: function(listener) {
                        return listeners.indexOf(listener) !== -1;
                    },
                    hasListeners: function() {
                        return listeners.length > 0;
                    }
                }
            };

            // The namespace owns the poll timer and the listeners, so it has to outlive the wrapper
            // it hangs off.
            retain(idle);
            return idle;
        }

        function makeMember(entry, path) {
            if (entry.kind === "event") {
                return makeEvent(path);
            }
            if (entry.kind === "managedStorage") {
                return makeManagedStorage();
            }
            if (entry.kind === "idle") {
                return makeIdle();
            }
            return makeStub(path);
        }

        function define(owner, key, value) {
            try {
                owner[key] = value;
                if (owner[key] === value) {
                    retain(owner);
                    return true;
                }
            } catch (error) {
                // A read-only or accessor-backed property; retry with defineProperty below.
            }
            try {
                Object.defineProperty(owner, key, {
                    value: value,
                    writable: true,
                    enumerable: true,
                    configurable: true
                });
                if (owner[key] === value) {
                    retain(owner);
                    return true;
                }
                return false;
            } catch (error) {
                return false;
            }
        }

        // `chrome.permissions` methods that answer like Chrome for permission names WebKit doesn't
        // know, where WebKit rejects the whole call. Calls WebKit accepts are left as they are.
        var invalidPermissionPattern = /is not a valid permission|invalid.*permission/i;
        var reportedUnknownPermissions = Object.create(null);
        var wrappedMarkerName = "__ddgWrapped";
        var wrappedPermissionsMethods = [
            { name: "contains", unknownNameFails: true },
            { name: "request", unknownNameFails: true },
            { name: "remove", unknownNameFails: false }
        ];

        function isInvalidPermissionError(error) {
            if (error === undefined || error === null) {
                return false;
            }
            var message = error.message === undefined || error.message === null ? String(error) : String(error.message);
            return invalidPermissionPattern.test(message);
        }

        function reportUnknownPermission(name) {
            if (reportedUnknownPermissions[name]) {
                return;
            }
            reportedUnknownPermissions[name] = true;
            if (typeof name === "string") {
                reportAPI("missing", "permission:" + name);
            }
            console.info("[DuckDuckGo] The host does not implement the '" + name
                + "' permission; answering the way Chrome would instead of throwing");
        }

        // A promise either way, whether the host throws or rejects.
        function callPermissionsMethod(method, owner, descriptor) {
            try {
                return Promise.resolve(method.call(owner, descriptor));
            } catch (error) {
                return Promise.reject(error);
            }
        }

        // Asks the host about one descriptor, and whether it knew the names in it. Other errors pass through.
        function probePermissionsDescriptor(method, owner, descriptor, name) {
            return callPermissionsMethod(method, owner, descriptor).then(function(result) {
                return { isKnown: true, isSatisfied: result === true };
            }, function(error) {
                if (!isInvalidPermissionError(error)) {
                    throw error;
                }
                if (name !== undefined) {
                    reportUnknownPermission(name);
                }
                return { isKnown: false, isSatisfied: false };
            });
        }

        function probePermissionsIndividually(method, owner, descriptor) {
            var names = descriptor && Array.isArray(descriptor.permissions) ? descriptor.permissions : [];
            var origins = descriptor && Array.isArray(descriptor.origins) ? descriptor.origins : [];
            var probes = names.map(function(name) {
                return probePermissionsDescriptor(method, owner, { permissions: [name] }, name);
            });
            if (origins.length > 0) {
                // Origins are never the reason for the validation error, so they stay one call.
                probes.push(probePermissionsDescriptor(method, owner, { origins: origins }, undefined));
            }
            return Promise.all(probes);
        }

        // An unknown name makes `contains` and `request` answer `false`; `remove` ignores it.
        function combinePermissionOutcomes(outcomes, unknownNameFails) {
            var isSatisfied = true;
            for (var index = 0; index < outcomes.length; index++) {
                if (!outcomes[index].isKnown) {
                    if (unknownNameFails) {
                        return false;
                    }
                } else if (!outcomes[index].isSatisfied) {
                    isSatisfied = false;
                }
            }
            return isSatisfied;
        }

        // A method bound to its owner, so destructured calls keep working, answering through a promise
        // and a trailing callback like the method it replaces.
        function makePermissionsMethod(owner, methodName, unknownNameFails) {
            var original = owner[methodName];
            if (typeof original !== "function" || original[wrappedMarkerName] === true) {
                return null;
            }

            var wrapper = function(descriptor) {
                var callback = arguments.length > 0 ? arguments[arguments.length - 1] : undefined;
                var promise = callPermissionsMethod(original, owner, descriptor).catch(function(error) {
                    if (!isInvalidPermissionError(error)) {
                        throw error;
                    }
                    return probePermissionsIndividually(original, owner, descriptor).then(function(outcomes) {
                        return combinePermissionOutcomes(outcomes, unknownNameFails);
                    });
                });
                if (typeof callback === "function") {
                    promise.then(function(value) {
                        invokeCallback(callback, value);
                    }, function() {
                        // A real failure only rejects the promise, as in Chrome.
                    });
                }
                return promise;
            };

            try {
                Object.defineProperty(wrapper, wrappedMarkerName, {
                    value: true,
                    writable: false,
                    enumerable: false,
                    configurable: true
                });
            } catch (error) {
                console.info("[DuckDuckGo] Could not mark the chrome.permissions." + methodName + " wrapper: " + error);
            }
            return wrapper;
        }


        var stubbedNamespaces = [];
        var stubbedMembers = [];
        var wrappedNamespaces = [];

        missingNamespaces.forEach(function(namespace) {
            try {
                if (api[namespace.name] !== undefined) {
                    return;
                }
                if (define(api, namespace.name, namespace.kind ? makeMember(namespace, namespace.name) : makeStub(namespace.name, true))) {
                    stubbedNamespaces.push(namespace.name);
                }
            } catch (error) {
                console.info("[DuckDuckGo] Could not stub chrome." + namespace.name + ": " + error);
            }
        });

        missingMembers.forEach(function(member) {
            try {
                var segments = member.path.split(".");
                var key = segments[segments.length - 1];
                var owner = api;
                for (var index = 0; index < segments.length - 1; index++) {
                    if (owner === undefined || owner === null) {
                        return;
                    }
                    owner = owner[segments[index]];
                }
                if (owner === undefined || owner === null || owner[key] !== undefined) {
                    return;
                }
                if (define(owner, key, makeMember(member, member.path))) {
                    stubbedMembers.push(member.path);
                }
            } catch (error) {
                console.info("[DuckDuckGo] Could not stub chrome." + member.path + ": " + error);
            }
        });

        // Only the methods that validate names are replaced; `getAll` and the events stay WebKit's.
        try {
            var permissions = api.permissions;
            if (permissions !== undefined && permissions !== null) {
                var wrappedMethodNames = [];
                wrappedPermissionsMethods.forEach(function(method) {
                    var wrapper = makePermissionsMethod(permissions, method.name, method.unknownNameFails);
                    if (wrapper !== null && define(permissions, method.name, wrapper)) {
                        wrappedMethodNames.push(method.name);
                    }
                });
                if (wrappedMethodNames.length > 0) {
                    wrappedNamespaces.push("permissions");
                }
            }
        } catch (error) {
            console.info("[DuckDuckGo] Could not wrap chrome.permissions: " + error);
        }

        if (stubbedNamespaces.length > 0 || stubbedMembers.length > 0 || wrappedNamespaces.length > 0) {
            console.info("[DuckDuckGo] Stubbed unavailable extension APIs — namespaces: ["
                + stubbedNamespaces.join(", ") + "], members: [" + stubbedMembers.join(", ")
                + "], wrapped: [" + wrappedNamespaces.join(", ") + "]");
        }
    })();

    """
}
