//
//  WebExtensionAPIStubScript.swift
//
//  Copyright © 2026 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import Foundation

/// JavaScript injected at document start into every page an extension owns, ahead of the
/// extension's own scripts (see `WebExtensionLoader`, which adds it for third-party extensions).
///
/// WebKit implements a subset of the `chrome.*` extension API. In a background page these
/// namespaces are undefined even when the matching permission is declared *and* granted:
/// `notifications`, `offscreen`, `downloads`, `idle`, `management`, `privacy`, `browsingData`,
/// `topSites`, `sidePanel`. Sub-namespaces and events on namespaces that *do* exist can be
/// missing too — `storage.managed` and `webNavigation.onCreatedNavigationTarget`, for instance.
///
/// Chrome builds routinely touch those APIs at the top level of their background script — the
/// Bitwarden extension calls `chrome.notifications.onClicked.addListener(...)` while wiring up its
/// listeners — and a missing namespace makes that a `TypeError` on the very first statement, which
/// aborts the whole startup: no listeners are registered and the extension never initializes.
///
/// Defining inert stubs for the missing pieces lets that top-level code run to completion, so the
/// listeners for the APIs WebKit *does* implement get registered and the extension comes up. The
/// stubbed calls themselves do nothing; the feature behind them stays unavailable either way, the
/// difference is whether the rest of the extension works. Most stubs are generic and resolve to
/// `undefined`; where callers read straight off the result — `storage.managed.get()` — the stub is
/// shaped to answer with the empty value Chrome would return.
///
/// One behavior of the host is worth calling out, established by measurement on macOS 26.6.2:
/// - `chrome.webNavigation`, `chrome.tabs` and friends are native wrapper objects that WebKit
///   discards once JavaScript stops referencing them, taking any property we added with them: an
///   event stub installed on `chrome.webNavigation` vanished within about half a second. The script
///   therefore parks every object it decorates in a retention array on `globalThis`, which kept the
///   stubs alive for the lifetime of the background page.
///
/// Note that stubs are only installed for names that are actually missing, so a future WebKit that
/// implements one of them wins automatically.
///
/// The script also reports its stub calls to the API compatibility log, through
/// `WebExtensionAPICompatibilityScript`.
public enum WebExtensionAPIStubScript {

    /// Property on `globalThis` holding the objects the script decorated, so WebKit's native
    /// namespace wrappers stay alive along with the stubs installed on them.
    static let retentionPropertyName = "__ddgRetainedExtensionAPINamespaces"

    public static let source = """
    // Generated by DuckDuckGo. Defines inert stubs for chrome.* APIs that WebKit does not
    // implement, so an extension's background script survives touching them at the top level.
    (function() {
        "use strict";

        // Whichever global the host exposes. We deliberately do not alias `chrome` to `browser`
        // (or the other way round) — that is WebKit's call to make, not ours.
        var api = globalThis.chrome || globalThis.browser;
        if (!api) {
            return;
        }

        // The script must leave ordinary web content alone: some websites define their own
        // `window.chrome` object to look like Chrome, and they must not get stubs installed on it,
        // nor the retention array leaked into them. Only extension pages are served over
        // `webkit-extension:`. A bare `JSContext` in tests has no `location`, so an absent
        // `location` still lets the script run.
        try {
            if (globalThis.location !== undefined && typeof globalThis.location.protocol === "string"
                && globalThis.location.protocol !== "webkit-extension:") {
                return;
            }
        } catch (error) {
            // Reading `location` should not throw; if it does, treat the frame as not ours.
            return;
        }

        // Our own extensions (autoconsent, content blocker, Dark Reader, …) declare
        // `browser_specific_settings.duckduckgo` and need no Chrome shims. Keep in sync with
        // `WKWebExtension.needsChromeCompatibility`.
        try {
            var settings = api.runtime && typeof api.runtime.getManifest === "function"
                ? api.runtime.getManifest().browser_specific_settings : undefined;
            if (settings && settings.duckduckgo) {
                return;
            }
        } catch (error) {
            // A page that cannot read its manifest is treated like any other extension page.
        }

        // Namespaces WebKit does not define at all. Each becomes a generic nestable stub.
        var missingNamespaces = [
            { name: "notifications" },
            { name: "offscreen" },
            { name: "downloads" },
            { name: "idle" },
            { name: "management" },
            { name: "privacy" },
            { name: "browsingData" },
            { name: "topSites" },
            { name: "sidePanel" }
        ];

        // Members missing from namespaces that WebKit does implement, addressed by dotted path.
        // A "namespace" member becomes a nestable stub, an "event" member an addListener object, and
        // "managedStorage" a purpose-shaped stub (see makeManagedStorage below).
        var missingMembers = [
            { path: "storage.managed", kind: "managedStorage" },
            { path: "webNavigation.onCreatedNavigationTarget", kind: "event" },
            { path: "runtime.onSuspend", kind: "event" }
        ];

        var retentionPropertyName = "\(Self.retentionPropertyName)";
        var eventNamePattern = /^on[A-Z]/;
        var stubDescription = "[DuckDuckGo API stub]";

        // WebKit hands out short-lived wrapper objects for its native namespaces and throws away
        // anything we added to one as soon as JavaScript stops referencing it. Parking every
        // decorated object here keeps both the wrapper and its stubs alive for the whole session.
        var retained = globalThis[retentionPropertyName];
        if (!Array.isArray(retained)) {
            retained = [];
            try {
                Object.defineProperty(globalThis, retentionPropertyName, {
                    value: retained,
                    writable: false,
                    enumerable: false,
                    configurable: true
                });
            } catch (error) {
                globalThis[retentionPropertyName] = retained;
            }
        }

        function retain(object) {
            // `globalThis` outlives everything, so keeping it here would only add noise.
            if (object && object !== globalThis && retained.indexOf(object) === -1) {
                retained.push(object);
            }
        }

        retain(api);

        // Reports a stub call through `WebExtensionAPICompatibilityScript`, which runs first in the same
        // pages. Without it, nothing is reported.
        function reportAPI(kind, path) {
            try {
                var report = globalThis["\(WebExtensionAPICompatibilityScript.reportFunctionName)"];
                if (typeof path === "string" && typeof report === "function") {
                    report(kind, path);
                }
            } catch (error) {
                // Reporting must never disturb the page.
            }
        }

        // Hands a trailing Chrome-style callback its value once, out of band, so a throwing
        // callback cannot take down the caller. Its error is thrown again from a timer, where it
        // surfaces as an uncaught error the page and the compatibility log can see.
        function invokeCallback(callback, value) {
            Promise.resolve().then(function() {
                try {
                    callback(value);
                } catch (error) {
                    setTimeout(function() {
                        throw error;
                    }, 0);
                }
            });
        }

        // A stubbed API method that answers with `makeValue()`, promise-style and callback-style.
        function makeResolver(makeValue) {
            return function() {
                var value = makeValue();
                var callback = arguments.length > 0 ? arguments[arguments.length - 1] : undefined;
                if (typeof callback === "function") {
                    invokeCallback(callback, value);
                }
                return Promise.resolve(value);
            };
        }

        // `path`, when given, names the API for the compatibility log: registering a listener counts
        // as using a stub. The events inside working shims pass no path.
        function makeEvent(path) {
            return {
                addListener: function() {
                    reportAPI("stubbed", path === undefined ? undefined : path + ".addListener");
                },
                removeListener: function() {},
                hasListener: function() {
                    return false;
                },
                hasListeners: function() {
                    return false;
                }
            };
        }

        // A callable, infinitely nestable placeholder: `chrome.privacy.services.passwordSavingEnabled.get()`
        // resolves through it without ever throwing, and any `onSomething` property is an event object.
        // `path` is the stub's API path, reported when it is called; reading a property is not a use.
        function makeStub(path) {
            var children = Object.create(null);

            return new Proxy(function() {}, {
                get: function(target, property) {
                    if (property === "then") {
                        // Never look like a thenable: awaiting or resolving a namespace must not hang.
                        return undefined;
                    }
                    if (property === Symbol.toPrimitive) {
                        return function() {
                            return stubDescription;
                        };
                    }
                    if (property === "toString") {
                        return function() {
                            return stubDescription;
                        };
                    }
                    if (typeof property !== "string") {
                        return undefined;
                    }
                    if (property === "call" || property === "apply" || property === "bind") {
                        // `stub.call(...)` is a call of the stub itself: the function's own methods must
                        // not extend the API path, or `chrome.downloads.download.call(...)` would be
                        // reported as `chrome.downloads.download.call`.
                        return Reflect.get(target, property);
                    }
                    if (!(property in children)) {
                        var childPath = path + "." + property;
                        children[property] = eventNamePattern.test(property) ? makeEvent(childPath) : makeStub(childPath);
                    }
                    return children[property];
                },
                apply: function(target, thisArgument, argumentsList) {
                    // `JSON.stringify` and `valueOf()` call these on any object; they are not API use.
                    if (!/\\.(toJSON|valueOf)$/.test(path)) {
                        reportAPI("stubbed", path);
                    }
                    // Support both API styles: hand `undefined` to a trailing callback, and return a
                    // promise for callers that await instead.
                    var callback = argumentsList.length > 0 ? argumentsList[argumentsList.length - 1] : undefined;
                    if (typeof callback === "function") {
                        invokeCallback(callback, undefined);
                    }
                    return Promise.resolve(undefined);
                }
            });
        }

        // `storage.managed` needs more than the generic stub: Chrome resolves `get()` to an object
        // (empty when no policy is set) and extensions read a key straight off the result, so
        // resolving to `undefined` would throw at their call site rather than ours. Every call gets
        // a fresh object, so a caller mutating one result cannot leak into the next.
        function makeManagedStorage() {
            return {
                get: makeResolver(function() {
                    return {};
                }),
                getBytesInUse: makeResolver(function() {
                    return 0;
                }),
                onChanged: makeEvent()
            };
        }

        function makeMember(entry, path) {
            if (entry.kind === "event") {
                return makeEvent(path);
            }
            if (entry.kind === "managedStorage") {
                return makeManagedStorage();
            }
            return makeStub(path);
        }

        function define(owner, key, value) {
            try {
                owner[key] = value;
                if (owner[key] === value) {
                    retain(owner);
                    return true;
                }
            } catch (error) {
                // A read-only or accessor-backed property; retry with defineProperty below.
            }
            try {
                Object.defineProperty(owner, key, {
                    value: value,
                    writable: true,
                    enumerable: true,
                    configurable: true
                });
                if (owner[key] === value) {
                    retain(owner);
                    return true;
                }
                return false;
            } catch (error) {
                return false;
            }
        }

        var stubbedNamespaces = [];
        var stubbedMembers = [];

        missingNamespaces.forEach(function(namespace) {
            try {
                if (api[namespace.name] !== undefined) {
                    return;
                }
                if (define(api, namespace.name, makeMember(namespace, namespace.name))) {
                    stubbedNamespaces.push(namespace.name);
                }
            } catch (error) {
                console.info("[DuckDuckGo] Could not stub chrome." + namespace.name + ": " + error);
            }
        });

        missingMembers.forEach(function(member) {
            try {
                var segments = member.path.split(".");
                var key = segments[segments.length - 1];
                var owner = api;
                for (var index = 0; index < segments.length - 1; index++) {
                    if (owner === undefined || owner === null) {
                        return;
                    }
                    owner = owner[segments[index]];
                }
                if (owner === undefined || owner === null || owner[key] !== undefined) {
                    return;
                }
                if (define(owner, key, makeMember(member, member.path))) {
                    stubbedMembers.push(member.path);
                }
            } catch (error) {
                console.info("[DuckDuckGo] Could not stub chrome." + member.path + ": " + error);
            }
        });

        if (stubbedNamespaces.length > 0 || stubbedMembers.length > 0) {
            console.info("[DuckDuckGo] Stubbed unavailable extension APIs — namespaces: ["
                + stubbedNamespaces.join(", ") + "], members: [" + stubbedMembers.join(", ") + "]");
        }
    })();

    """
}
