//
//  WebExtensionAPIStubScript.swift
//
//  Copyright © 2026 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import Foundation

/// JavaScript injected into the background page generated by `WebExtensionBackgroundPagePatcher`,
/// ahead of the extension's own background script.
///
/// WebKit implements a subset of the `chrome.*` extension API. In a background page these
/// namespaces are undefined even when the matching permission is declared *and* granted:
/// `notifications`, `offscreen`, `downloads`, `idle`, `management`, `privacy`, `browsingData`,
/// `topSites`, `sidePanel`, `dns`. A handful of events on namespaces that *do* exist are missing
/// too, for instance `chrome.webNavigation.onCreatedNavigationTarget`.
///
/// Chrome builds routinely touch those APIs at the top level of their background script — the
/// 1Password extension calls `chrome.notifications.onClicked.addListener(...)` while wiring up its
/// listeners — and a missing namespace makes that a `TypeError` on the very first statement, which
/// aborts the whole startup: no listeners are registered and the extension never initializes.
///
/// Defining inert stubs for the missing pieces lets that top-level code run to completion, so the
/// listeners for the APIs WebKit *does* implement get registered and the extension comes up. The
/// stubbed calls themselves do nothing; the feature behind them stays unavailable either way, the
/// difference is whether the rest of the extension works.
///
/// Note that stubs are only installed for names that are actually missing, so a future WebKit that
/// implements one of them wins automatically.
enum WebExtensionAPIStubScript {

    /// Name of the stub script, written next to `manifest.json`.
    static let filename = "ddg-api-stubs.js"

    static let source = """
    // Generated by DuckDuckGo. Defines inert stubs for chrome.* APIs that WebKit does not
    // implement, so an extension's background script survives touching them at the top level.
    (function() {
        "use strict";

        // Whichever global the host exposes. We deliberately do not alias `chrome` to `browser`
        // (or the other way round) — that is WebKit's call to make, not ours.
        var api = globalThis.chrome || globalThis.browser;
        if (!api) {
            return;
        }

        var missingNamespaces = [
            "notifications",
            "offscreen",
            "downloads",
            "idle",
            "management",
            "privacy",
            "browsingData",
            "topSites",
            "sidePanel",
            "dns"
        ];

        // Events missing from namespaces that WebKit does implement, as "namespace.event".
        var missingEvents = [
            "webNavigation.onCreatedNavigationTarget",
            "webNavigation.onHistoryStateUpdated",
            "webNavigation.onReferenceFragmentUpdated",
            "webNavigation.onTabReplaced",
            "tabs.onZoomChange",
            "runtime.onSuspend",
            "runtime.onSuspendCanceled",
            "runtime.onUpdateAvailable",
            "runtime.onRestartRequired"
        ];

        var eventNamePattern = /^on[A-Z]/;
        var stubDescription = "[DuckDuckGo API stub]";

        function makeEvent() {
            return {
                addListener: function() {},
                removeListener: function() {},
                hasListener: function() {
                    return false;
                },
                hasListeners: function() {
                    return false;
                }
            };
        }

        // A callable, infinitely nestable placeholder: `chrome.privacy.services.passwordSavingEnabled.get()`
        // resolves through it without ever throwing, and any `onSomething` property is an event object.
        function makeStub() {
            var children = Object.create(null);

            return new Proxy(function() {}, {
                get: function(target, property) {
                    if (property === "then") {
                        // Never look like a thenable: awaiting or resolving a namespace must not hang.
                        return undefined;
                    }
                    if (property === Symbol.toPrimitive) {
                        return function() {
                            return stubDescription;
                        };
                    }
                    if (property === "toString") {
                        return function() {
                            return stubDescription;
                        };
                    }
                    if (typeof property !== "string") {
                        return undefined;
                    }
                    if (!(property in children)) {
                        children[property] = eventNamePattern.test(property) ? makeEvent() : makeStub();
                    }
                    return children[property];
                },
                apply: function(target, thisArgument, argumentsList) {
                    // Support both API styles: hand `undefined` to a trailing callback, and return a
                    // promise for callers that await instead.
                    var callback = argumentsList.length > 0 ? argumentsList[argumentsList.length - 1] : undefined;
                    if (typeof callback === "function") {
                        Promise.resolve().then(function() {
                            try {
                                callback(undefined);
                            } catch (error) {
                                console.info("[DuckDuckGo] Stubbed API callback threw: " + error);
                            }
                        });
                    }
                    return Promise.resolve(undefined);
                }
            });
        }

        function define(owner, key, value) {
            try {
                owner[key] = value;
                if (owner[key] === value) {
                    return true;
                }
            } catch (error) {
                // A read-only or accessor-backed property; retry with defineProperty below.
            }
            try {
                Object.defineProperty(owner, key, {
                    value: value,
                    writable: true,
                    enumerable: true,
                    configurable: true
                });
                return owner[key] === value;
            } catch (error) {
                return false;
            }
        }

        var stubbedNamespaces = [];
        var stubbedEvents = [];

        missingNamespaces.forEach(function(namespace) {
            try {
                if (api[namespace] !== undefined) {
                    return;
                }
                if (define(api, namespace, makeStub())) {
                    stubbedNamespaces.push(namespace);
                }
            } catch (error) {
                console.info("[DuckDuckGo] Could not stub chrome." + namespace + ": " + error);
            }
        });

        missingEvents.forEach(function(path) {
            try {
                var separator = path.indexOf(".");
                var namespace = path.slice(0, separator);
                var event = path.slice(separator + 1);
                var owner = api[namespace];
                if (!owner || owner[event] !== undefined) {
                    return;
                }
                if (define(owner, event, makeEvent())) {
                    stubbedEvents.push(path);
                }
            } catch (error) {
                console.info("[DuckDuckGo] Could not stub chrome." + path + ": " + error);
            }
        });

        if (stubbedNamespaces.length > 0 || stubbedEvents.length > 0) {
            console.info("[DuckDuckGo] Stubbed unavailable extension APIs — namespaces: ["
                + stubbedNamespaces.join(", ") + "], events: [" + stubbedEvents.join(", ") + "]");
        }
    })();

    """
}
