//
//  WebExtensionAPICompatibilityScript.swift
//
//  Copyright © 2026 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import Foundation

/// Reports which unsupported `chrome.*` APIs a third-party extension's pages run into, for the API
/// compatibility log (see `WebExtensionAPICompatibilityLog`).
///
/// It watches the errors a page raises or logs (`error`, `unhandledrejection`, `console.error`,
/// `console.warn`) and posts the ones shaped like a missing or rejected API to
/// `messageHandlerName`; the browser classifies their text and never keeps it. Other scripts report
/// through `reportFunctionName`, a function the script leaves on `globalThis`.
public enum WebExtensionAPICompatibilityScript {

    /// Name of the script message handler the page reports to. It is optional: a page with no
    /// handler of this name reports nothing.
    public static let messageHandlerName = "ddgWebExtensionAPICompatibility"

    /// Function on `globalThis` that other scripts call with a kind and an API path to report it.
    static let reportFunctionName = "__ddgReportAPICompatibility"

    public static let source = """
    // Generated by DuckDuckGo. Reports unsupported chrome.* API use to the browser.
    (function() {
        "use strict";

        var api = globalThis.chrome || globalThis.browser;
        if (!api) {
            return;
        }

        // Only extension pages are served over `webkit-extension:`; websites that define their own
        // `window.chrome` are left alone. A bare `JSContext` in tests has no `location`.
        try {
            if (globalThis.location !== undefined && typeof globalThis.location.protocol === "string"
                && globalThis.location.protocol !== "webkit-extension:") {
                return;
            }
        } catch (error) {
            return;
        }

        // Reports unsupported API use to the browser, which logs the kind and the API path only.
        // "stubbed" and "missing" carry the API path; "error" carries an error message that the
        // browser classifies and discards. Everything here is best effort: it never throws, never
        // prevents an event's default action and stays quiet when the host has no such handler.
        var compatibilityHandlerName = "\(Self.messageHandlerName)";
        var compatibilityReports = Object.create(null);
        var apiReportCount = 0;
        var errorReportCount = 0;
        var maximumAPIReports = 200;
        // Errors get a budget of their own, so a page that logs a lot of errors cannot use up the
        // reports for stubbed and missing APIs.
        var maximumErrorReports = 50;
        var maximumErrorMessageLength = 300;
        var isReporting = false;

        // Only text shaped like an error about an API leaves the page; everything else stays here.
        // The browser classifies these further (and is the one place that decides what is logged).
        var reportableErrorFragments = ["is not an object (evaluating '", "is not a function. (In '", "Invalid call to ",
            "Can't find variable: ", " is not defined."];

        function isReportableErrorMessage(message) {
            return reportableErrorFragments.some(function(fragment) {
                return message.indexOf(fragment) !== -1;
            });
        }

        function postCompatibilityReport(payload, dedupeKey) {
            var isError = payload.kind === "error";
            if (isReporting || compatibilityReports[dedupeKey]
                || (isError ? errorReportCount >= maximumErrorReports : apiReportCount >= maximumAPIReports)) {
                return;
            }
            isReporting = true;
            try {
                var handlers = globalThis.webkit && globalThis.webkit.messageHandlers;
                var handler = handlers && handlers[compatibilityHandlerName];
                if (handler && typeof handler.postMessage === "function") {
                    compatibilityReports[dedupeKey] = true;
                    if (isError) {
                        errorReportCount += 1;
                    } else {
                        apiReportCount += 1;
                    }
                    handler.postMessage(payload);
                }
            } catch (error) {
                // Reporting must never disturb the page.
            } finally {
                isReporting = false;
            }
        }

        function reportAPI(kind, path) {
            if (typeof path === "string") {
                postCompatibilityReport({ kind: kind, api: path }, kind + " " + path);
            }
        }

        function reportErrorMessage(message) {
            if (typeof message === "string" && isReportableErrorMessage(message)) {
                var trimmed = message.slice(0, maximumErrorMessageLength);
                postCompatibilityReport({ kind: "error", message: trimmed }, "error " + trimmed);
            }
        }

        function messageOf(value) {
            try {
                if (typeof value === "string") {
                    return value;
                }
                if (value && typeof value.message === "string") {
                    return value.message;
                }
            } catch (error) {
                // A value that throws on access carries no usable message.
            }
            return undefined;
        }

        function installCompatibilityHooks() {
            var installedMarker = "__ddgAPICompatibilityHooksInstalled";
            try {
                if (globalThis[installedMarker] === true || typeof globalThis.addEventListener !== "function") {
                    return;
                }
                Object.defineProperty(globalThis, installedMarker, {
                    value: true,
                    writable: false,
                    enumerable: false,
                    configurable: true
                });
            } catch (error) {
                return;
            }

            globalThis.addEventListener("error", function(event) {
                reportErrorMessage(messageOf(event && event.error) || messageOf(event && event.message));
            });
            globalThis.addEventListener("unhandledrejection", function(event) {
                reportErrorMessage(messageOf(event && event.reason));
            });

            // The wrapper is what Web Inspector shows as the top frame of a logged message, instead of
            // the caller. That is accepted: wrapping is the only way to see what Angular's
            // ErrorHandler prints, which is how Bitwarden surfaces caught errors.
            ["error", "warn"].forEach(function(methodName) {
                try {
                    var original = globalThis.console && globalThis.console[methodName];
                    if (typeof original !== "function") {
                        return;
                    }
                    globalThis.console[methodName] = function() {
                        try {
                            for (var index = 0; index < Math.min(arguments.length, 5); index++) {
                                reportErrorMessage(messageOf(arguments[index]));
                            }
                        } catch (error) {
                            // Never let reporting stop the page from logging.
                        }
                        return original.apply(this, arguments);
                    };
                } catch (error) {
                    // A frozen console is left as it is.
                }
            });
        }

        installCompatibilityHooks();

        try {
            Object.defineProperty(globalThis, "\(Self.reportFunctionName)", {
                value: reportAPI,
                writable: false,
                enumerable: false,
                configurable: false
            });
        } catch (error) {
            // Another copy of the script got there first.
        }
    })();
    """
}
