//
//  SharedDesignSystemColor.swift
//
//  Copyright © 2025 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import Foundation

/// Autogenerated from [Figma](https://www.figma.com/design/3W4vi0zX8hrpQc7zInQQB6/%F0%9F%8E%A8-Global-Colors---Styles?m=dev)
/// Do not edit by hand — re-export from Figma and regenerate.
public enum SharedDesignSystemColor: CaseIterable {

    // MARK: - Surface
    /// Used for deep background layers (e.g., behind tab bars).
    case surfaceBackdrop
    /// Used for high-level content areas such as Settings and other full-page views within the UI.
    case surfaceCanvas
    /// The main background of the UI.
    case surfacePrimary
    /// Background for cards, side panels, or overlays.
    case surfaceSecondary
    /// Used for input fields, form elements, and subtle background variations in nested components.
    case surfaceTertiary
    case surfaceContrast
    case surfaceDecorationPrimary
    case surfaceDecorationSecondary
    case surfaceDecorationTertiary

    // MARK: - Container
    case containerFillPrimary
    case containerFillSecondary
    case containerFillTertiary
    case containerBorderPrimary
    case containerBorderSecondary
    case containerBorderTertiary

    // MARK: - Text
    case textPrimary
    case textSecondary
    /// Does not pass accessibility for contrast. Only use for disabled states or incidental or purely decorative elements.
    case textTertiary

    // MARK: - Icons
    case iconsPrimary
    case iconsSecondary
    case iconsTertiary

    // MARK: - Accent
    case accentPrimary
    case accentSecondary
    case accentTertiary
    case accentQuaternary
    case accentGlowPrimary
    case accentGlowSecondary
    case accentTextPrimary
    case accentTextSecondary
    case accentTextTertiary
    case accentContentPrimary
    case accentContentSecondary
    case accentContentTertiary

    // MARK: - Accent-Alt
    case accentAltPrimary
    case accentAltSecondary
    case accentAltTertiary
    case accentAltGlowPrimary
    case accentAltGlowSecondary
    case accentAltTextPrimary
    case accentAltTextSecondary
    case accentAltTextTertiary
    case accentAltContentPrimary
    case accentAltContentSecondary
    case accentAltContentTertiary

    // MARK: - Accent-Fire
    case accentFirePrimary
    case accentFireSecondary
    case accentFireTertiary
    case accentFireGlowPrimary
    case accentFireGlowSecondary
    case accentFireTextPrimary
    case accentFireTextSecondary
    case accentFireTextTertiary
    case accentFireContentPrimary
    case accentFireContentSecondary
    case accentFireContentTertiary

    // MARK: - Accent-Brand
    case accentBrandPrimary
    case accentBrandSecondary
    case accentBrandTertiary
    case accentBrandGlowPrimary
    case accentBrandGlowSecondary
    case accentBrandTextPrimary
    case accentBrandTextSecondary
    case accentBrandTextTertiary
    case accentBrandContentPrimary
    case accentBrandContentSecondary
    case accentBrandContentTertiary

    // MARK: - Control
    case controlFillPrimary
    case controlFillSecondary
    case controlFillTertiary
    case controlBorderPrimary
    case controlBorderSecondary
    case controlBorderTertiary
    case controlBorderQuaternary

    // MARK: - Control-Subtle
    case controlSubtleFillPrimary
    case controlSubtleFillSecondary
    case controlSubtleFillTertiary
    case controlSubtleBorderPrimary
    case controlSubtleBorderSecondary
    case controlSubtleBorderTertiary

    // MARK: - Control-Raised
    case controlRaisedFillPrimary
    case controlRaisedFillSecondary
    case controlRaisedFillTertiary
    case controlRaisedBackdrop

    // MARK: - Unified-Input
    case unifiedInputFillPrimary
    case unifiedInputFieldFillActive
    case unifiedInputFieldFillResting

    // MARK: - Highlight
    case highlightPrimary

    // MARK: - Tone
    case toneTintPrimary
    case toneTintSecondary
    case toneShadePrimary

    // MARK: - Shadow
    case shadowPrimary
    case shadowSecondary
    case shadowTertiary

    // MARK: - Destructive
    case destructivePrimary
    case destructiveSecondary
    case destructiveTertiary
    case destructiveGlowPrimary
    case destructiveGlowSecondary
    case destructiveTextPrimary
    case destructiveTextSecondary
    case destructiveTextTertiary
    case destructiveContentPrimary
    case destructiveContentSecondary
    case destructiveContentTertiary

    // MARK: - Status
    case statusGreen
    case statusYellowPrimary
    case statusYellowSecondary
    case statusYellowTertiary
    case statusRed
    case statusGray

    // MARK: - Status-Warning
    case statusWarningPrimary
    case statusWarningContentPrimary
    case statusWarningFillPrimary

    // MARK: - Manual tokens
    // Not in Figma. Declared in ManualColorTokens.swift.

    // Alert
    case alertGreen
    case alertYellow

    // VPN
    case vpnGreen
    case vpnGreenPressed
    case vpnGreenForeground
    case vpnGreenForegroundPressed
    case vpnYellow
    case vpnYellowPressed
    case vpnYellowForeground
    case vpnYellowForegroundPressed

    // Shield
    case shieldPrivacy

    // Buttons
    case buttonsWhite
    case buttonsPrimaryDefault
    case buttonsPrimaryPressed
    case buttonsPrimaryDisabled
    case buttonsPrimaryText
    case buttonsPrimaryTextDisabled
    case buttonsSecondaryFillDefault
    case buttonsSecondaryFillPressed
    case buttonsSecondaryFillDisabled
    case buttonsSecondaryFillText
    case buttonsSecondaryFillTextDisabled

    // System
    case lines
    case spinnerStart
    case spinnerFinal

    // Text
    case textSuccess
    case textLink

    // iOS Surfaces
    case backgroundTertiary
    case backgroundSheets
    case backgroundPromptMessage
    case urlBar
    case surfaceDecorationQuaternary
    case border

    // iOS Text
    case textPlaceholder

    // iOS Buttons
    case buttonsSecondaryWireDefault
    case buttonsSecondaryWirePressedFill
    case buttonsSecondaryWireDisabledStroke
    case buttonsSecondaryWireText
    case buttonsSecondaryWireTextPressed
    case buttonsSecondaryWireTextDisabled
    case buttonsGhostPressedFill
    case buttonsGhostText
    case buttonsGhostTextPressed
    case buttonsGhostTextDisabled
    case buttonsDeleteGhostPressedFill
    case buttonsDeleteGhostText
    case buttonsDeleteGhostTextPressed
    case buttonsDeleteGhostTextDisabled
    case buttonsDestructivePrimaryPressed

    // Permission Center
    case permissionCenterBackground
    case permissionCenterContainerBackground
    case permissionWarningBackground
    case permissionReloadButtonBackground
    case permissionReloadButtonText

    // MARK: - Palette-backed names
    // Not in Figma under this name, but identical to a token that is, so the
    // resolver takes the value from the palette rather than a fixed pair.
    case textSelectionFill
}

public typealias DesignSystemColor = SharedDesignSystemColor

// MARK: - Compatibility aliases

/// Temporary. Figma renamed these tokens; the aliases keep existing call sites
/// compiling until the scripted rename sweep, which deletes them.
public extension SharedDesignSystemColor {

    static var controlsBorderPrimary: Self { .controlBorderPrimary }
    static var controlsBorderQuaternary: Self { .controlBorderQuaternary }
    static var controlsBorderSecondary: Self { .controlBorderSecondary }
    static var controlsBorderTertiary: Self { .controlBorderTertiary }
    static var controlsFillPrimary: Self { .controlFillPrimary }
    static var controlsFillSecondary: Self { .controlFillSecondary }
    static var controlsFillTertiary: Self { .controlFillTertiary }
    static var controlsRaisedBackdrop: Self { .controlRaisedBackdrop }
    static var controlsRaisedFillPrimary: Self { .controlRaisedFillPrimary }
    static var controlsRaisedFillSecondary: Self { .controlRaisedFillSecondary }
    static var controlsRaisedFillTertiary: Self { .controlRaisedFillTertiary }
    static var controlsSubtleBorderPrimary: Self { .controlSubtleBorderPrimary }
    static var controlsSubtleBorderSecondary: Self { .controlSubtleBorderSecondary }
    static var controlsSubtleBorderTertiary: Self { .controlSubtleBorderTertiary }
    static var controlsSubtleFillSecondary: Self { .controlSubtleFillSecondary }
    static var destructiveGlow: Self { .destructiveGlowPrimary }
    static var inputActive: Self { .unifiedInputFieldFillActive }
    static var inputResting: Self { .unifiedInputFieldFillResting }
    static var statusYellow: Self { .statusYellowPrimary }
}
