//
//  DesertColorPalette.swift
//
//  Copyright © 2025 DuckDuckGo. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import SwiftUI

#if os(macOS)

/// Autogenerated from [Figma](https://www.figma.com/design/3W4vi0zX8hrpQc7zInQQB6/%F0%9F%8E%A8-Global-Colors---Styles?m=dev)
/// Do not edit by hand — re-export from Figma and regenerate.
struct DesertColorPalette: SharedColorPaletteDefinition {

    // MARK: - Surface
    static let surfaceBackdrop = DynamicColor(lightHex: 0xC6B99F, darkHex: 0x1C1A17)
    static let surfaceCanvas = DynamicColor(lightHex: 0xF5F4EF, darkHex: 0x322F2A)
    static let surfacePrimary = DynamicColor(lightHex: 0xEFEAE1, darkHex: 0x37342F)
    static let surfaceSecondary = DynamicColor(lightHex: 0xF5F4EF, darkHex: 0x423E38)
    static let surfaceTertiary = DynamicColor(lightHex: 0xFBFAF9, darkHex: 0x4A463F)
    static let surfaceContrast = DynamicColor(lightHex: 0x736249, lightOpacity: 0.12,
                                              darkHex: 0xEDE8DE, darkOpacity: 0.96)
    static let surfaceDecorationPrimary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.12,
                                                       darkHex: 0xEDE8DE, darkOpacity: 0.12)
    static let surfaceDecorationSecondary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.2,
                                                         darkHex: 0xEDE8DE, darkOpacity: 0.2)
    static let surfaceDecorationTertiary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.32,
                                                        darkHex: 0xEDE8DE, darkOpacity: 0.32)

    // MARK: - Container
    static let containerFillPrimary = DynamicColor(lightHex: 0x17150F, lightOpacity: 0.01,
                                                   darkHex: 0xF9F8F6, darkOpacity: 0.03)
    static let containerFillSecondary = DynamicColor(lightHex: 0x17150F, lightOpacity: 0.03,
                                                     darkHex: 0xF9F8F6, darkOpacity: 0.06)
    static let containerFillTertiary = DynamicColor(lightHex: 0x17150F, lightOpacity: 0.06,
                                                    darkHex: 0xF9F8F6, darkOpacity: 0.09)
    static let containerBorderPrimary = DynamicColor(lightHex: 0x17150F, lightOpacity: 0.06,
                                                     darkHex: 0xF9F8F6, darkOpacity: 0.09)
    static let containerBorderSecondary = DynamicColor(lightHex: 0x17150F, lightOpacity: 0.09,
                                                       darkHex: 0xF9F8F6, darkOpacity: 0.12)
    static let containerBorderTertiary = DynamicColor(lightHex: 0x17150F, lightOpacity: 0.12,
                                                      darkHex: 0xF9F8F6, darkOpacity: 0.16)

    // MARK: - Text
    static let textPrimary = DynamicColor(lightHex: 0x17150F, lightOpacity: 0.96, darkHex: 0xFEFCFB, darkOpacity: 0.96)
    static let textSecondary = DynamicColor(lightHex: 0x17150F, lightOpacity: 0.6, darkHex: 0xFEFCFB, darkOpacity: 0.66)
    static let textTertiary = DynamicColor(lightHex: 0x17150F, lightOpacity: 0.36, darkHex: 0xFEFCFB, darkOpacity: 0.36)

    // MARK: - Icons
    static let iconsPrimary = DynamicColor(lightHex: 0x17150F, lightOpacity: 0.84, darkHex: 0xFDFAF7, darkOpacity: 0.78)
    static let iconsSecondary = DynamicColor(lightHex: 0x17150F, lightOpacity: 0.66,
                                             darkHex: 0xFDFAF7, darkOpacity: 0.48)
    static let iconsTertiary = DynamicColor(lightHex: 0x17150F, lightOpacity: 0.36,
                                            darkHex: 0xFDFAF7, darkOpacity: 0.24)

    // MARK: - Accent
    static let accentPrimary = DynamicColor(lightHex: 0xD14200, darkHex: 0xFFA53D)
    static let accentSecondary = DynamicColor(lightHex: 0xC23700, darkHex: 0xFF8A14)
    static let accentTertiary = DynamicColor(lightHex: 0xB83100, darkHex: 0xFF6A00)
    static let accentQuaternary = DynamicColor(lightHex: 0xA32C00, darkHex: 0xD65900)
    static let accentGlowPrimary = DynamicColor(lightHex: 0xD14200, lightOpacity: 0.2,
                                                darkHex: 0xFFA53D, darkOpacity: 0.2)
    static let accentGlowSecondary = DynamicColor(lightHex: 0xD14200, lightOpacity: 0.12,
                                                  darkHex: 0xFFA53D, darkOpacity: 0.12)
    static let accentTextPrimary = DynamicColor(lightHex: 0xC23700, darkHex: 0xFFCC66)
    static let accentTextSecondary = DynamicColor(lightHex: 0xB83100, darkHex: 0xFFA53D)
    static let accentTextTertiary = DynamicColor(lightHex: 0xA32C00, darkHex: 0xFF6A00)
    static let accentContentPrimary = DynamicColor(lightHex: 0xFDFDFC, darkHex: 0x17150F)
    static let accentContentSecondary = DynamicColor(lightHex: 0xFDFDFC, lightOpacity: 0.7,
                                                     darkHex: 0x17150F, darkOpacity: 0.7)
    static let accentContentTertiary = DynamicColor(lightHex: 0xFDFDFC, lightOpacity: 0.5,
                                                    darkHex: 0x17150F, darkOpacity: 0.5)

    // MARK: - Accent-Alt
    static let accentAltPrimary = DynamicColor(lightHex: 0xFFB866, darkHex: 0xD14200)
    static let accentAltSecondary = DynamicColor(lightHex: 0xFFA53D, darkHex: 0xC23700)
    static let accentAltTertiary = DynamicColor(lightHex: 0xFF8A14, darkHex: 0xB83100)
    static let accentAltGlowPrimary = DynamicColor(lightHex: 0xFFA53D, lightOpacity: 0.2,
                                                   darkHex: 0xFFA53D, darkOpacity: 0.2)
    static let accentAltGlowSecondary = DynamicColor(lightHex: 0xFFA53D, lightOpacity: 0.12,
                                                     darkHex: 0xFFA53D, darkOpacity: 0.12)
    static let accentAltTextPrimary = DynamicColor(lightHex: 0xC23700, darkHex: 0xFFCC66)
    static let accentAltTextSecondary = DynamicColor(lightHex: 0xB83100, darkHex: 0xFFA53D)
    static let accentAltTextTertiary = DynamicColor(lightHex: 0xA32C00, darkHex: 0xFF6A00)
    static let accentAltContentPrimary = DynamicColor(lightHex: 0x331100, darkHex: 0xFDFAF7)
    static let accentAltContentSecondary = DynamicColor(lightHex: 0x331100, lightOpacity: 0.7,
                                                        darkHex: 0xFDFAF7, darkOpacity: 0.7)
    static let accentAltContentTertiary = DynamicColor(lightHex: 0x331100, lightOpacity: 0.5,
                                                       darkHex: 0xFDFAF7, darkOpacity: 0.5)

    // MARK: - Accent-Fire
    static let accentFirePrimary = DynamicColor(lightColor: RebrandingColor.Mandarin.mandarin50,
                                                darkColor: RebrandingColor.Mandarin.mandarin40)
    static let accentFireSecondary = DynamicColor(lightColor: RebrandingColor.Mandarin.mandarin60,
                                                  darkColor: RebrandingColor.Mandarin.mandarin50)
    static let accentFireTertiary = DynamicColor(lightColor: RebrandingColor.Mandarin.mandarin70,
                                                 darkColor: RebrandingColor.Mandarin.mandarin60)
    static let accentFireGlowPrimary = DynamicColor(lightHex: 0xF05F2B, lightOpacity: 0.2,
                                                    darkHex: 0xFF8D5C, darkOpacity: 0.2)
    static let accentFireGlowSecondary = DynamicColor(lightHex: 0xF05F2B, lightOpacity: 0.12,
                                                      darkHex: 0xFF8D5C, darkOpacity: 0.12)
    static let accentFireTextPrimary = DynamicColor(lightColor: RebrandingColor.Mandarin.mandarin50,
                                                    darkColor: RebrandingColor.Mandarin.mandarin40)
    static let accentFireTextSecondary = DynamicColor(lightColor: RebrandingColor.Mandarin.mandarin60,
                                                      darkColor: RebrandingColor.Mandarin.mandarin50)
    static let accentFireTextTertiary = DynamicColor(lightColor: RebrandingColor.Mandarin.mandarin70,
                                                     darkColor: RebrandingColor.Mandarin.mandarin60)
    static let accentFireContentPrimary = DynamicColor(lightHex: 0xFFFFFF, darkHex: 0xFFFFFF)
    static let accentFireContentSecondary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.7,
                                                         darkHex: 0xFFFFFF, darkOpacity: 0.7)
    static let accentFireContentTertiary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.5,
                                                        darkHex: 0xFFFFFF, darkOpacity: 0.5)

    // MARK: - Accent-Brand
    static let accentBrandPrimary = DynamicColor(lightHex: 0xFFB866, darkHex: 0xFFB866)
    static let accentBrandSecondary = DynamicColor(lightHex: 0xFFA53D, darkHex: 0xFFA53D)
    static let accentBrandTertiary = DynamicColor(lightHex: 0xFF8A14, darkHex: 0xFF8A14)
    static let accentBrandGlowPrimary = DynamicColor(lightHex: 0xFFA53D, lightOpacity: 0.2,
                                                     darkHex: 0xFFA53D, darkOpacity: 0.2)
    static let accentBrandGlowSecondary = DynamicColor(lightHex: 0xFFA53D, lightOpacity: 0.12,
                                                       darkHex: 0xFFA53D, darkOpacity: 0.12)
    static let accentBrandTextPrimary = DynamicColor(lightHex: 0xC23700, darkHex: 0xC23700)
    static let accentBrandTextSecondary = DynamicColor(lightHex: 0xB83100, darkHex: 0xB83100)
    static let accentBrandTextTertiary = DynamicColor(lightHex: 0xA32C00, darkHex: 0xA32C00)
    static let accentBrandContentPrimary = DynamicColor(lightHex: 0x331100, darkHex: 0x331100)
    static let accentBrandContentSecondary = DynamicColor(lightHex: 0x331100, lightOpacity: 0.7,
                                                          darkHex: 0x331100, darkOpacity: 0.7)
    static let accentBrandContentTertiary = DynamicColor(lightHex: 0x331100, lightOpacity: 0.5,
                                                         darkHex: 0x331100, darkOpacity: 0.5)

    // MARK: - Control
    static let controlFillPrimary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.09,
                                                 darkHex: 0xEDE8DE, darkOpacity: 0.12)
    static let controlFillSecondary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.12,
                                                   darkHex: 0xEDE8DE, darkOpacity: 0.18)
    static let controlFillTertiary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.18,
                                                  darkHex: 0xEDE8DE, darkOpacity: 0.24)
    static let controlBorderPrimary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.32,
                                                   darkHex: 0xEDE8DE, darkOpacity: 0.32)
    static let controlBorderSecondary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.48,
                                                     darkHex: 0xEDE8DE, darkOpacity: 0.48)
    static let controlBorderTertiary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.64,
                                                    darkHex: 0xEDE8DE, darkOpacity: 0.64)
    static let controlBorderQuaternary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.72,
                                                      darkHex: 0xEDE8DE, darkOpacity: 0.72)

    // MARK: - Control-Subtle
    static let controlSubtleFillPrimary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.03,
                                                       darkHex: 0xEDE8DE, darkOpacity: 0.12)
    static let controlSubtleFillSecondary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.08,
                                                         darkHex: 0xEDE8DE, darkOpacity: 0.18)
    static let controlSubtleFillTertiary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.1,
                                                        darkHex: 0xEDE8DE, darkOpacity: 0.24)
    static let controlSubtleBorderPrimary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.12,
                                                         darkHex: 0xEDE8DE, darkOpacity: 0.12)
    static let controlSubtleBorderSecondary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.18,
                                                           darkHex: 0xEDE8DE, darkOpacity: 0.18)
    static let controlSubtleBorderTertiary = DynamicColor(lightHex: 0x736249, lightOpacity: 0.36,
                                                          darkHex: 0xEDE8DE, darkOpacity: 0.36)

    // MARK: - Control-Raised
    static let controlRaisedFillPrimary = DynamicColor(lightHex: 0xFBFAF9, lightOpacity: 1,
                                                       darkHex: 0xF5FAF4, darkOpacity: 0.18)
    static let controlRaisedFillSecondary = DynamicColor(lightHex: 0xFBFAF9, lightOpacity: 1,
                                                         darkHex: 0xF5FAF4, darkOpacity: 0.18)
    static let controlRaisedFillTertiary = DynamicColor(lightHex: 0xFBFAF9, lightOpacity: 1,
                                                        darkHex: 0xF5FAF4, darkOpacity: 0.18)
    static let controlRaisedBackdrop = DynamicColor(lightHex: 0x000000, lightOpacity: 0.09,
                                                    darkHex: 0xFFFFFF, darkOpacity: 0.12)

    // MARK: - Unified-Input
    static let unifiedInputFillPrimary = DynamicColor(lightHex: 0xFBFAF9,
                                                      darkHex: 0xFBFAF9)  // light-only in Figma; dark mirrors light
    static let unifiedInputFieldFillActive = DynamicColor(lightHex: 0xFBFAF9, darkHex: 0x4A463F)
    static let unifiedInputFieldFillResting = DynamicColor(lightHex: 0xE1D9CA, darkHex: 0x4A463F)

    // MARK: - Highlight
    static let highlightPrimary = DynamicColor(lightHex: 0xFDFAF7, lightOpacity: 0.24,
                                               darkHex: 0xF5FAF4, darkOpacity: 0.12)

    // MARK: - Tone
    static let toneTintPrimary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.32,
                                              darkHex: 0xEDE8DE, darkOpacity: 0.06)
    static let toneTintSecondary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.6,
                                                darkHex: 0xEDE8DE, darkOpacity: 0.12)
    static let toneShadePrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.06,
                                               darkHex: 0x13110C, darkOpacity: 0.16)

    // MARK: - Shadow
    static let shadowPrimary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.05,
                                            darkHex: 0x000000, darkOpacity: 0.16)
    static let shadowSecondary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.08,
                                              darkHex: 0x000000, darkOpacity: 0.24)
    static let shadowTertiary = DynamicColor(lightHex: 0x000000, lightOpacity: 0.16,
                                             darkHex: 0x000000, darkOpacity: 0.32)

    // MARK: - Destructive
    static let destructivePrimary = DynamicColor(lightHex: 0xEE1025, darkHex: 0xEE1025)
    static let destructiveSecondary = DynamicColor(lightHex: 0xD21527, darkHex: 0xD21527)
    static let destructiveTertiary = DynamicColor(lightHex: 0xAA1926, darkHex: 0xAA1926)
    static let destructiveGlowPrimary = DynamicColor(lightHex: 0xEE1025, lightOpacity: 0.2,
                                                     darkHex: 0xEE1025, darkOpacity: 0.2)
    static let destructiveGlowSecondary = DynamicColor(lightHex: 0xEE1025, lightOpacity: 0.2,
                                                       darkHex: 0xEE1025, darkOpacity: 0.12)
    static let destructiveTextPrimary = DynamicColor(lightHex: 0xEE1025, darkHex: 0xEE1025)
    static let destructiveTextSecondary = DynamicColor(lightHex: 0xD21527, darkHex: 0xD21527)
    static let destructiveTextTertiary = DynamicColor(lightHex: 0xAA1926, darkHex: 0xAA1926)
    static let destructiveContentPrimary = DynamicColor(lightHex: 0xFFFFFF, darkHex: 0x000000)
    static let destructiveContentSecondary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.9,
                                                          darkHex: 0x000000, darkOpacity: 0.9)
    static let destructiveContentTertiary = DynamicColor(lightHex: 0xFFFFFF, lightOpacity: 0.6,
                                                         darkHex: 0x000000, darkOpacity: 0.6)

    // MARK: - Status
    static let statusGreen = DynamicColor(lightColor: RebrandingColor.Green.green50, darkColor: Color(0x21C000))
    static let statusYellowPrimary = DynamicColor(lightColor: Color(0xFFCC00), darkColor: Color(0xFFCC00))
    static let statusYellowSecondary = DynamicColor(lightColor: Color(0xFFCC00), darkColor: Color(0xFFCC00))
    static let statusYellowTertiary = DynamicColor(lightColor: Color(0xFFCC00), darkColor: Color(0xFFCC00))
    static let statusRed = DynamicColor(lightColor: RebrandingColor.Red.red50, darkColor: Color(0xEB102D))
    static let statusGray = DynamicColor(lightColor: Color(0xAAAAAA), darkColor: Color(0xAAAAAA))

    // MARK: - Status-Warning
    static let statusWarningPrimary = DynamicColor(lightColor: Color(0xFFCC00), darkColor: Color(0xFFCC00))
    static let statusWarningContentPrimary = DynamicColor(lightColor: Color(0x191101), darkColor: Color(0x191101))
    static let statusWarningFillPrimary = DynamicColor(lightColor: Color(0xFFE699).opacity(0.32),
                                                       darkColor: Color(0xFFB200).opacity(0.12))
}

#endif
