name: iOS - Shared Web Tests

on:
  push:
    branches: [ main, "release/**", "jkt/shared-web-tests" ]
  pull_request:
  workflow_call:
    inputs:
      branch:
        description: "Branch name"
        required: false
        type: string
      skip-release:
        description: "Skip release build"
        required: false
        default: false
        type: boolean
    secrets:
      APPLE_API_KEY_BASE64:
        required: true
      APPLE_API_KEY_ID:
        required: true
      APPLE_API_KEY_ISSUER:
        required: true
      ASANA_ACCESS_TOKEN:
        required: true
      MATCH_PASSWORD:
        required: true
      SSH_PRIVATE_KEY_FASTLANE_MATCH:
        required: true

jobs:
  shared-web-tests:
    name: Shared web tests

    runs-on: macos-15
    timeout-minutes: 20
    steps:
    - name: Check out the code
      if: github.event_name == 'pull_request' || github.event_name == 'push'
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_$(<.xcode-version).app/Contents/Developer

    - name: Checkout shared web tests
      uses: actions/checkout@v4
      with:
        submodules: recursive
        repository: duckduckgo/shared-web-tests
        path: shared-web-tests
        ref: jkt/webdriver
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Test
      run: |
          cd shared-web-tests
          npm run build

    - name: Build iOS
      run: |
        source .maestro/common.sh
        project_root=$(pwd)
        build_app

    - name: Run tests
      run: |
        cd shared-web-tests
        brew install python@3.9 && /opt/homebrew/bin/python3.9 -m venv venv39 && source venv39/bin/activate
        sudo npm run install-hosts
        source ../.maestro/common.sh
        export DERIVED_DATA_PATH="$derived_data_path"
        export TARGET_DEVICE="iPhone-16"
        export TARGET_OS="iOS-18-2"
        npm run test | tee test-output.log

    - name: Upload logs when workflow failed
      uses: actions/upload-artifact@v4
      if: failure() || cancelled()
      with:
        name: BuildLogs
        path: |
          test-output.log
        retention-days: 7


  create-asana-task:
    name: Create Asana Task
    needs: [shared-web-tests]

    if: failure() && github.ref_name == 'main' && github.run_attempt == 1

    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Create Asana Task
        uses: ./.github/actions/asana-failed-pr-checks
        with:
          action: create-task
          asana-access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana-section-id: 1209511873385229
          commit-author: ${{ needs.unit-tests.outputs.commit_author }}

  