name: Test - Create Release Asana Task

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform
        required: true
        type: choice
        options: [ios, macos]
      tag:
        description: Tag to use (e.g., 7.123.0-1+ios or 1.123.0-1+macos)
        required: true
        type: string
      asana_project:
        description: Asana Project ID (leave empty to use Apple Deployments project ID)
        required: false
        type: string
      asana_section_id:
        description: Asana Section ID (leave empty to use default section)
        required: false
        type: string
  push:
    branches:
      - 'sam/send-asana-release-notification-task'

jobs:
  test-create:
    runs-on: ubuntu-latest
    env:
      EFFECTIVE_ASANA_PROJECT: ${{ inputs.asana_project != '' && inputs.asana_project || vars.APPLE_DEPLOYMENTS_ASANA_PROJECT_ID }}
      EFFECTIVE_ASANA_SECTION: ${{ inputs.asana_section_id != '' && inputs.asana_section_id || vars.APPLE_DEPLOYMENTS_SECTION_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create iOS release notification task
        uses: ./.github/actions/send-release-notification-task
        with:
          platform: "ios"
          tag: "7.180.0-0+ios"
          asana-project: ${{ env.EFFECTIVE_ASANA_PROJECT }}
          asana-access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana-section: ${{ env.EFFECTIVE_ASANA_SECTION }}

      - name: Create macOS release notification task
        uses: ./.github/actions/send-release-notification-task
        with:
          platform: "macos"
          tag: "1.150.0.0"
          asana-project: ${{ env.EFFECTIVE_ASANA_PROJECT }}
          asana-section: ${{ env.EFFECTIVE_ASANA_SECTION }}
          asana-access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
