name: macOS - Test Sentry Grouping Rules

defaults:
  run:
    working-directory: macOS

on:
  workflow_dispatch:
  push:

jobs:
  export-notarized-app:

    name: Test Sentry Grouping Rules

    runs-on: macos-15

    steps:
    - name: Register SSH key for certificates repository access
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FASTLANE_MATCH }}

    - name: Check out the code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up fastlane
      run: bundle install

    - name: Update Sentry grouping rules
      id: update-grouping-rules
      continue-on-error: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
        DSYM_S3_PATH: s3://${{ vars.DSYM_BUCKET_NAME }}/${{ vars.MACOS_DSYM_BUCKET_RULES_PREFIX }}/
      run: |
        bundle exec fastlane run generate_sentry_grouping_rules platform:macos output_file:grouping-rules.txt
        aws s3 cp grouping-rules.txt ${{ env.DSYM_S3_PATH }}
